// Couple self-serve signup: create account, confirm email, set up the
// wedding, and the "almost ready" home shown until the wedding is activated.
//
// App Store rule (guidelines 3.1.1 / 3.1.3), owner decision Sep 29 2026:
// only the United States storefront may show a way to activate on the web.
// Everything the app shows elsewhere comes from the `pending` block, which
// deliberately carries NO price, NO purchase wording and NO call to action
// to pay. The `us` block is the only place those words are allowed, and it
// renders only when StoreKit reports the "USA" storefront (src/lib/storefront).
// BUILD-LOG decision 12 (the banned-word grep gate) applies here too.

import type { IconName } from "@/ui/Icon";

const en = {
  signUp: {
    label: "For couples",
    title: "Create your account.",
    intro: "Set up your wedding in two minutes. Your guests will thank you.",
    apple: "Continue with Apple",
    google: "Continue with Google",
    orEmail: "or with email",
    emailPlaceholder: "you@example.com",
    passwordPlaceholder: "Password, at least 8 characters",
    emailLabel: "Email",
    passwordLabel: "Password, at least 8 characters",
    show: "Show",
    hide: "Hide",
    create: "Create my account",
    legal: "By creating an account you agree to the Terms and the Privacy Policy.",
    terms: "Terms",
    privacy: "Privacy Policy",
    haveAccount: "Already have an account?",
    newHere: "First time with Guest-ly?",
    createLink: "Create an account",
    entrance: "Getting married? Create your account",
    signIn: "Sign in",
    errEmail: "Enter a valid email address.",
    errPassword: "Use at least 8 characters.",
    errNetwork: "We could not reach Guest-ly. Check your connection and try again.",
    errUnknown: "We could not create your account. Please try again.",
    errSocialNew: "New accounts with Apple or Google are not open yet. Create your account with your email instead.",
  },
  verify: {
    label: "Confirm your email",
    title: "Check your inbox.",
    intro: "We sent a code to {email}. Enter it here to finish creating your account.",
    codeLabel: "Confirmation code",
    confirm: "Confirm",
    resend: "Send a new code",
    resent: "A new code is on its way.",
    resendIn: "You can ask for a new one in {s} s.",
    changeEmail: "Use a different email",
    spam: "Nothing yet? Look in your spam or promotions folder.",
    errCode: "That code is not right or has expired. Check it or send a new one.",
    errRate: "Too many tries. Please wait a few minutes and try again.",
    errNetwork: "We could not reach Guest-ly. Check your connection and try again.",
  },
  setup: {
    label: "Your wedding",
    title: "Tell us about the big day.",
    intro: "This is what your guests will see first. You can change any of it later.",
    you: "Your name",
    partner: "Your partner's name",
    youPlaceholder: "Ana",
    partnerPlaceholder: "Luis",
    date: "Wedding date",
    datePick: "Choose the date",
    dateTbd: "We have not picked a date yet",
    city: "City",
    cityPlaceholder: "Cartagena",
    country: "Country",
    countryPlaceholder: "Colombia",
    language: "Language for your guests",
    english: "English",
    spanish: "Español",
    create: "Create our wedding",
    signedInAs: "Signed in as {email}",
    signOut: "Sign out",
    errNames: "Enter both names.",
    errCity: "Enter the city of the wedding.",
    errUnknown: "We could not create your wedding. Please try again.",
    errNotEligible: "This account cannot create a wedding here. Sign in with the account Guest-ly or your planner set up for you.",
  },
  calendar: {
    prev: "Previous month",
    next: "Next month",
    done: "Done",
    clear: "No date yet",
    weekdays: ["M", "T", "W", "T", "F", "S", "S"],
  },
  pending: {
    label: "Almost ready",
    daysToGo: { one: "1 day to go", other: "{n} days to go" },
    today: "Today is the day",
    dateTbd: "Date to be decided",
    title: "Your wedding is almost ready.",
    emailed: "We sent the details to activate your wedding to {email}.",
    emailedAgo: "Sent {when}",
    resend: "Resend email",
    resent: "Sent. Check your inbox and spam folder.",
    resendError: "We could not send the email. Please try again.",
    refresh: "Refresh",
    refreshing: "Checking",
    stillPending: "Not active yet. It updates on its own a minute after activation.",
    unlocksTitle: "What unlocks",
    unlocks: [
      { icon: "guests" as IconName, title: "Guest list and RSVPs", body: "Parties, plus-ones, per-event answers, reminders." },
      { icon: "chat" as IconName, title: "Your concierge", body: "Answers your guests on WhatsApp and the web, in their language." },
      { icon: "globe" as IconName, title: "Wedding website", body: "Your story, schedule, hotels and gifts, in English and Spanish." },
      { icon: "star" as IconName, title: "Seating, budget and the day itself", body: "Tables, vendors, run of show and QR check-in at the door." },
    ],
    preview: "Take the tour",
    previewBody: "See how Guest-ly works before your wedding is live.",
    account: "Account",
    signOut: "Sign out",
    deleteAccount: "Delete account",
    deleteConfirm: "This deletes your account and the wedding you set up. It cannot be undone.",
    deleteCancel: "Cancel",
    deleted: "Your account has been deleted.",
    deleteError: "We could not delete your account. Please try again.",
    live: "Your wedding is live.",
  },
  us: {
    cta: "Choose your plan",
    note: "Opens the Guest-ly website in your browser. Come back here when you are done.",
  },
  lockedWrite: "Your wedding is not active yet, so changes are paused.",
};

export type SignupCopy = typeof en;

const es: SignupCopy = {
  signUp: {
    label: "Para parejas",
    title: "Crea tu cuenta.",
    intro: "Arma tu boda en dos minutos. Tus invitados te lo van a agradecer.",
    apple: "Continuar con Apple",
    google: "Continuar con Google",
    orEmail: "o con tu correo",
    emailPlaceholder: "tu@correo.com",
    passwordPlaceholder: "Contraseña, mínimo 8 caracteres",
    emailLabel: "Correo electrónico",
    passwordLabel: "Contraseña, mínimo 8 caracteres",
    show: "Ver",
    hide: "Ocultar",
    create: "Crear mi cuenta",
    legal: "Al crear una cuenta aceptas los Términos y la Política de privacidad.",
    terms: "Términos",
    privacy: "Política de privacidad",
    haveAccount: "¿Ya tienes una cuenta?",
    newHere: "¿Primera vez en Guest-ly?",
    createLink: "Crea una cuenta",
    entrance: "¿Te casas? Crea tu cuenta",
    signIn: "Inicia sesión",
    errEmail: "Escribe un correo válido.",
    errPassword: "Usa al menos 8 caracteres.",
    errNetwork: "No pudimos conectar con Guest-ly. Revisa tu conexión e inténtalo de nuevo.",
    errUnknown: "No pudimos crear tu cuenta. Inténtalo de nuevo.",
    errSocialNew: "Todavía no se pueden crear cuentas nuevas con Apple o Google. Crea tu cuenta con tu correo.",
  },
  verify: {
    label: "Confirma tu correo",
    title: "Revisa tu correo.",
    intro: "Te enviamos un código a {email}. Escríbelo aquí para terminar de crear tu cuenta.",
    codeLabel: "Código de confirmación",
    confirm: "Confirmar",
    resend: "Enviar un código nuevo",
    resent: "Te enviamos un código nuevo.",
    resendIn: "Puedes pedir uno nuevo en {s} s.",
    changeEmail: "Usar otro correo",
    spam: "¿No te llega? Revisa la carpeta de spam o promociones.",
    errCode: "Ese código no es correcto o ya venció. Revísalo o pide uno nuevo.",
    errRate: "Demasiados intentos. Espera unos minutos e inténtalo de nuevo.",
    errNetwork: "No pudimos conectar con Guest-ly. Revisa tu conexión e inténtalo de nuevo.",
  },
  setup: {
    label: "Tu boda",
    title: "Cuéntanos del gran día.",
    intro: "Es lo primero que verán tus invitados. Puedes cambiar todo después.",
    you: "Tu nombre",
    partner: "El nombre de tu pareja",
    youPlaceholder: "Ana",
    partnerPlaceholder: "Luis",
    date: "Fecha de la boda",
    datePick: "Elige la fecha",
    dateTbd: "Todavía no tenemos fecha",
    city: "Ciudad",
    cityPlaceholder: "Cartagena",
    country: "País",
    countryPlaceholder: "Colombia",
    language: "Idioma para tus invitados",
    english: "English",
    spanish: "Español",
    create: "Crear nuestra boda",
    signedInAs: "Sesión iniciada como {email}",
    signOut: "Cerrar sesión",
    errNames: "Escribe los dos nombres.",
    errCity: "Escribe la ciudad de la boda.",
    errUnknown: "No pudimos crear tu boda. Inténtalo de nuevo.",
    errNotEligible: "Esta cuenta no puede crear una boda aquí. Inicia sesión con la cuenta que Guest-ly o tu planner creó para ti.",
  },
  calendar: {
    prev: "Mes anterior",
    next: "Mes siguiente",
    done: "Listo",
    clear: "Sin fecha por ahora",
    weekdays: ["L", "M", "M", "J", "V", "S", "D"],
  },
  pending: {
    label: "Casi lista",
    daysToGo: { one: "Falta 1 día", other: "Faltan {n} días" },
    today: "Hoy es el gran día",
    dateTbd: "Fecha por definir",
    title: "Tu boda está casi lista.",
    emailed: "Te enviamos a {email} los detalles para activar tu boda.",
    emailedAgo: "Enviado el {when}",
    resend: "Reenviar correo",
    resent: "Enviado. Revisa tu bandeja de entrada y la carpeta de spam.",
    resendError: "No pudimos enviar el correo. Inténtalo de nuevo.",
    refresh: "Actualizar",
    refreshing: "Revisando",
    stillPending: "Todavía no está activa. Se actualiza sola un minuto después de activarla.",
    unlocksTitle: "Lo que se desbloquea",
    unlocks: [
      { icon: "guests" as IconName, title: "Invitados y confirmaciones", body: "Grupos, acompañantes, respuestas por evento, recordatorios." },
      { icon: "chat" as IconName, title: "Tu asistente", body: "Responde a tus invitados por WhatsApp y en la web, en su idioma." },
      { icon: "globe" as IconName, title: "Página de la boda", body: "Tu historia, el programa, hoteles y regalos, en español e inglés." },
      { icon: "star" as IconName, title: "Mesas, presupuesto y el gran día", body: "Mesas, proveedores, cronograma y check-in con QR en la puerta." },
    ],
    preview: "Ver el recorrido",
    previewBody: "Mira cómo funciona Guest-ly antes de que tu boda esté activa.",
    account: "Cuenta",
    signOut: "Cerrar sesión",
    deleteAccount: "Eliminar cuenta",
    deleteConfirm: "Esto elimina tu cuenta y la boda que configuraste. No se puede deshacer.",
    deleteCancel: "Cancelar",
    deleted: "Tu cuenta fue eliminada.",
    deleteError: "No pudimos eliminar tu cuenta. Inténtalo de nuevo.",
    live: "Tu boda ya está activa.",
  },
  us: {
    cta: "Elige tu plan",
    note: "Abre el sitio de Guest-ly en tu navegador. Vuelve aquí cuando termines.",
  },
  lockedWrite: "Tu boda todavía no está activa, así que los cambios están en pausa.",
};

export const COPY = { en, es };
