// Broadcasts copy, EN + neutral LatAm ES (usted).

export const COPY = {
  en: {
    title: "Broadcasts",
    subtitle: "WhatsApp messages to your guests, through the approved templates.",
    newBroadcast: "New broadcast",
    history: "Sent",
    historyEmpty: "Nothing sent yet.",
    historyEmptyBody: "Your first broadcast will appear here with its delivery counts.",
    noPhones: "No guest has a phone number yet. Add phones on the guest list first.",
    recipients: "{n} recipients",
    sentOf: "{sent} of {total} sent",
    failed: "{n} failed",
    delivered: "{n} delivered",
    read: "{n} read",
    pending: "{n} pending",
    unknownBatch: "Sent from the concierge",
    messages: "{n} messages",
    // composer
    stepAudience: "Who receives it",
    stepMessage: "What they receive",
    stepReview: "Review and send",
    audience: "Audience",
    pickGuests: "Pick guests one by one",
    pickedGuests: "{n} guests picked",
    withPhone: "{n} with a phone",
    withoutPhone: "{n} without a phone will be skipped",
    template: "Approved template",
    custom: "Custom message",
    customHint: "Custom text only reaches guests who wrote to the concierge in the last 24 hours. WhatsApp rules, not ours.",
    language: "Language",
    langAuto: "Each guest's own",
    langEs: "Spanish for all",
    langEn: "English for all",
    fillIn: "Fill in",
    preview: "Preview",
    sample: "What {name} will see",
    perLang: "{es} in Spanish, {en} in English",
    review: "Review",
    sendTo: "Send to {n}",
    confirmTitle: "This cannot be undone",
    confirmBody: "WhatsApp messages go out immediately and cannot be recalled. Each message has a cost. Type SEND to confirm.",
    confirmWord: "SEND",
    confirmPlaceholder: "Type SEND",
    send: "Send now",
    sending: "Sending",
    cancel: "Cancel",
    sentTitle: "Sent",
    sentBody: "{sent} of {total} messages went out. {failed} failed.",
    done: "Done",
    noRecipients: "No one in this audience has a phone number.",
    readOnly: "Only the couple can send. Ask them to add you as an editor.",
    searchGuests: "Search guests",
    selectAll: "Select all shown",
    clear: "Clear",
    noPhone: "no phone",
    detail: "Broadcast",
    recipientList: "Recipients",
    ok: "sent",
    notOk: "failed",
    // planner
    plannerTitle: "Reminders",
    plannerSubtitle: "Sends happen through the couple. File a reminder request and they approve it.",
    plannerRequest: "Ask the couple to send reminders",
    plannerAudiences: "Who could be reached",
    plannerPhones: "{with} guests with a phone, {without} without",
  },
  es: {
    title: "Mensajes masivos",
    subtitle: "Mensajes de WhatsApp a sus invitados, con las plantillas aprobadas.",
    newBroadcast: "Nuevo mensaje",
    history: "Enviados",
    historyEmpty: "Todavía no se ha enviado nada.",
    historyEmptyBody: "Su primer mensaje masivo aparecerá aquí con sus conteos de entrega.",
    noPhones: "Ningún invitado tiene teléfono todavía. Agregue teléfonos en la lista de invitados primero.",
    recipients: "{n} destinatarios",
    sentOf: "{sent} de {total} enviados",
    failed: "{n} fallidos",
    delivered: "{n} entregados",
    read: "{n} leídos",
    pending: "{n} pendientes",
    unknownBatch: "Enviado desde el concierge",
    messages: "{n} mensajes",
    stepAudience: "Quién lo recibe",
    stepMessage: "Qué reciben",
    stepReview: "Revisar y enviar",
    audience: "Destinatarios",
    pickGuests: "Elegir invitados uno por uno",
    pickedGuests: "{n} invitados elegidos",
    withPhone: "{n} con teléfono",
    withoutPhone: "{n} sin teléfono se omitirán",
    template: "Plantilla aprobada",
    custom: "Mensaje personalizado",
    customHint: "El texto libre solo llega a quienes escribieron al concierge en las últimas 24 horas. Son reglas de WhatsApp, no nuestras.",
    language: "Idioma",
    langAuto: "El de cada invitado",
    langEs: "Español para todos",
    langEn: "Inglés para todos",
    fillIn: "Complete",
    preview: "Vista previa",
    sample: "Lo que verá {name}",
    perLang: "{es} en español, {en} en inglés",
    review: "Revisar",
    sendTo: "Enviar a {n}",
    confirmTitle: "Esto no se puede deshacer",
    confirmBody: "Los mensajes de WhatsApp salen de inmediato y no se pueden retirar. Cada mensaje tiene un costo. Escriba ENVIAR para confirmar.",
    confirmWord: "ENVIAR",
    confirmPlaceholder: "Escriba ENVIAR",
    send: "Enviar ahora",
    sending: "Enviando",
    cancel: "Cancelar",
    sentTitle: "Enviado",
    sentBody: "Salieron {sent} de {total} mensajes. {failed} fallaron.",
    done: "Listo",
    noRecipients: "Nadie en este grupo tiene teléfono.",
    readOnly: "Solo la pareja puede enviar. Pídales que lo agreguen como editor.",
    searchGuests: "Buscar invitados",
    selectAll: "Seleccionar los mostrados",
    clear: "Limpiar",
    noPhone: "sin teléfono",
    detail: "Mensaje masivo",
    recipientList: "Destinatarios",
    ok: "enviado",
    notOk: "fallido",
    plannerTitle: "Recordatorios",
    plannerSubtitle: "Los envíos pasan por la pareja. Presente una solicitud de recordatorio y ellos la aprueban.",
    plannerRequest: "Pedir a la pareja que envíe recordatorios",
    plannerAudiences: "A quién se podría llegar",
    plannerPhones: "{with} invitados con teléfono, {without} sin teléfono",
  },
};
