// Broadcasts copy, EN + neutral LatAm ES (tú).

export const COPY = {
  en: {
    title: "Broadcasts",
    subtitle: "WhatsApp messages to your guests, through the approved templates.",
    newBroadcast: "New broadcast",
    history: "Sent",
    historyEmpty: "Nothing sent yet.",
    historyEmptyBody: "Your first broadcast will appear here with its delivery counts.",
    noPhones: "No guest has a phone number yet. Add phones on the guest list first.",
    recipients: "{n} recipients",
    sentOf: "{sent} of {total} sent",
    failed: "{n} failed",
    delivered: "{n} delivered",
    read: "{n} read",
    pending: "{n} pending",
    unknownBatch: "Sent from the concierge",
    messages: "{n} messages",
    // composer
    stepAudience: "Who receives it",
    stepMessage: "What they receive",
    stepReview: "Review and send",
    audience: "Audience",
    pickGuests: "Pick guests one by one",
    pickedGuests: "{n} guests picked",
    withPhone: "{n} with a phone",
    withoutPhone: "{n} without a phone will be skipped",
    updatingPreview: "Updating preview...",
    recipientsChanged: "Who gets this message changed. Nothing was sent. Check the new count and confirm again.",
    template: "Approved template",
    templateNames: { invite: "Invitation", rsvp_reminder: "RSVP reminder", event_reminder: "Event reminder", general_update: "General update" },
    custom: "Custom message",
    customHint: "Custom text only reaches guests who wrote to the concierge in the last 24 hours. WhatsApp rules, not ours.",
    language: "Language",
    langAuto: "Each guest's own",
    langEs: "Spanish for all",
    langEn: "English for all",
    fillIn: "Fill in",
    preview: "Preview",
    sample: "What {name} will see",
    perLang: "{es} in Spanish, {en} in English",
    review: "Review",
    sendTo: "Send to {n}",
    confirmTitle: "This cannot be undone",
    confirmBody: "WhatsApp messages go out immediately and cannot be recalled. Each message has a cost. Type SEND to confirm.",
    confirmWord: "SEND",
    confirmPlaceholder: "Type SEND",
    send: "Send now",
    sending: "Sending",
    cancel: "Cancel",
    sentTitle: "Sent",
    sentBody: "{sent} of {total} messages went out. {failed} failed.",
    done: "Done",
    sendUnknownTitle: "Sending may have gone through",
    sendUnknownBody: "The connection dropped before Guest-ly answered. Check the Sent list before you send again, so no guest gets it twice.",
    viewSent: "Check the Sent list",
    noRecipients: "No one in this audience has a phone number.",
    readOnly: "Only the couple can send. Ask them to add you as an editor.",
    searchGuests: "Search guests",
    selectAll: "Select all shown",
    clear: "Clear",
    noPhone: "no phone",
    detail: "Broadcast",
    recipientList: "Recipients",
    ok: "sent",
    notOk: "failed",
    // planner
    plannerTitle: "Reminders",
    plannerSubtitle: "Sends happen through the couple. File a reminder request and they approve it.",
    plannerRequest: "Ask the couple to send reminders",
    plannerAudiences: "Who could be reached",
    plannerPhones: "{with}, {without} without",
    plannerWithPhone: { one: "{n} guest with a phone", other: "{n} guests with a phone" },
    // Build 13: the Broadcast tab, per-wedding templates, template requests
    tabTitle: "Broadcast",
    tabSubtitle: "WhatsApp messages to your guests, with templates approved for your wedding.",
    notReadyTitle: "Broadcasts aren't set up yet",
    notReadyBody: "WhatsApp only lets you message guests with templates it has approved for your wedding, and yours doesn't have one yet. Request one and the Guest-ly team takes it to WhatsApp for you.",
    notReadyBodyNoRequest: "WhatsApp only lets you message guests with templates it has approved for your wedding, and yours doesn't have one yet. Write to Guest-ly to set one up.",
    yourTemplates: "Your templates",
    templatesEmpty: "No approved templates yet.",
    langNames: { en: "English", es: "Spanish" },
    demo: "Demo",
    demoNote: "Demo wedding: messages are not delivered.",
    demoSent: "Demo wedding: this was recorded, nothing was delivered.",
    requestTemplate: "Request a template",
    requestTemplateSub: "A new message type, reviewed by WhatsApp",
    requestLimit: "You have 3 requests in progress. Wait for one to finish, or cancel one.",
    yourRequests: "Your requests",
    status: {
      submitted: "Submitted",
      in_review: "In review",
      needs_info: "Needs info",
      with_whatsapp: "With WhatsApp",
      approved: "Approved",
      rejected: "Rejected",
      cancelled: "Cancelled",
    },
    kinds: {
      rsvp_closing: "RSVP deadline",
      transport: "Transport",
      thank_you: "Thank you",
      schedule_change: "Schedule change",
      welcome: "Welcome",
      meal_choice: "Meal choice",
      other: "Something else",
    },
    teamNote: "Note from Guest-ly",
    // request form
    formTitle: "Request a template",
    formEditTitle: "Edit your request",
    formLead: "The Guest-ly team reviews it and takes it to WhatsApp for approval. Nothing reaches your guests until it is approved and you send it.",
    formKind: "What is it for",
    formName: "Name it",
    formNamePlaceholder: "For example: Shuttle times",
    formPurpose: "What should it say",
    formPurposePlaceholder: "What guests need to know, and why",
    formWhen: "When you'd send it",
    formWhenPlaceholder: "For example: the week before the wedding",
    formLanguages: "Languages",
    formDraftEn: "Draft in English (optional)",
    formDraftEs: "Draft in Spanish (optional)",
    formDraftPlaceholder: "Your wording, if you have one in mind",
    formSend: "Send request",
    formSave: "Save changes",
    formMissing: "Add a name and what it should say.",
    formLangMissing: "Pick at least one language.",
    formSent: "Request sent. We will let you know when it moves.",
    formSaved: "Request updated.",
    formFailed: "The request could not be sent. Try again.",
    requestEdit: "Edit request",
    requestCancel: "Cancel request",
    requestCancelTitle: "Cancel this request?",
    requestCancelBody: "The Guest-ly team stops working on it. You can send a new one any time.",
    requestKeep: "Keep it",
    requestCancelled: "Request cancelled.",
    requestSentOn: "Sent {when}",
    requestUpdated: "Updated {when}",
    close: "Close",
    // composer, build 13
    templateMissing: "Your {name} template isn't set up yet",
    templateMissingBody: "WhatsApp has to approve it for your wedding first. Request it and we will tell you when it is ready.",
    templateChanged: "This template changed. Review it again before sending.",
    oneLanguage: "This template is only in {lang}. Every guest gets it in {lang}.",
    // planner, build 13
    plannerTabTitle: "Broadcast",
    plannerTabSubtitle: "The couple sends WhatsApp messages. You can see their templates, ask them to send, and request a new template.",
    plannerAsk: "Ask the couple to send",
    plannerTemplatesNote: "Only the couple can send these.",
    plannerTemplates: "The couple's templates",
    plannerNotReady: "WhatsApp only lets the couple message guests with templates it has approved for this wedding, and it has none yet. Request one and the Guest-ly team takes it to WhatsApp.",
  },
  es: {
    title: "Mensajes masivos",
    subtitle: "Mensajes de WhatsApp a tus invitados, con las plantillas aprobadas.",
    newBroadcast: "Nuevo mensaje",
    history: "Enviados",
    historyEmpty: "Todavía no se ha enviado nada.",
    historyEmptyBody: "Tu primer mensaje masivo aparecerá aquí con sus conteos de entrega.",
    noPhones: "Ningún invitado tiene teléfono todavía. Agrega teléfonos en la lista de invitados primero.",
    recipients: "{n} destinatarios",
    sentOf: "{sent} de {total} enviados",
    failed: "{n} fallidos",
    delivered: "{n} entregados",
    read: "{n} leídos",
    pending: "{n} pendientes",
    unknownBatch: "Enviado desde el concierge",
    messages: "{n} mensajes",
    stepAudience: "Quién lo recibe",
    stepMessage: "Qué reciben",
    stepReview: "Revisar y enviar",
    audience: "Destinatarios",
    pickGuests: "Elegir invitados uno por uno",
    pickedGuests: "{n} invitados elegidos",
    withPhone: "{n} con teléfono",
    withoutPhone: "{n} sin teléfono se omitirán",
    updatingPreview: "Actualizando vista previa...",
    recipientsChanged: "Cambió quién recibe este mensaje. No se envió nada. Revisa el nuevo número y vuelve a confirmar.",
    template: "Plantilla aprobada",
    templateNames: { invite: "Invitación", rsvp_reminder: "Recordatorio de RSVP", event_reminder: "Recordatorio de evento", general_update: "Aviso general" },
    custom: "Mensaje personalizado",
    customHint: "El texto libre solo llega a quienes escribieron al concierge en las últimas 24 horas. Son reglas de WhatsApp, no nuestras.",
    language: "Idioma",
    langAuto: "El de cada invitado",
    langEs: "Español para todos",
    langEn: "Inglés para todos",
    fillIn: "Completa",
    preview: "Vista previa",
    sample: "Lo que verá {name}",
    perLang: "{es} en español, {en} en inglés",
    review: "Revisar",
    sendTo: "Enviar a {n}",
    confirmTitle: "Esto no se puede deshacer",
    confirmBody: "Los mensajes de WhatsApp salen de inmediato y no se pueden retirar. Cada mensaje tiene un costo. Escribe ENVIAR para confirmar.",
    confirmWord: "ENVIAR",
    confirmPlaceholder: "Escribe ENVIAR",
    send: "Enviar ahora",
    sending: "Enviando",
    cancel: "Cancelar",
    sentTitle: "Enviado",
    sentBody: "Salieron {sent} de {total} mensajes. {failed} fallaron.",
    done: "Listo",
    sendUnknownTitle: "Puede que el envío haya salido",
    sendUnknownBody: "La conexión se cortó antes de que Guest-ly respondiera. Revisa la lista de enviados antes de volver a enviar, para que ningún invitado lo reciba dos veces.",
    viewSent: "Ver la lista de enviados",
    noRecipients: "Nadie en este grupo tiene teléfono.",
    readOnly: "Solo la pareja puede enviar. Pídeles que te agreguen como editor.",
    searchGuests: "Buscar invitados",
    selectAll: "Seleccionar los mostrados",
    clear: "Limpiar",
    noPhone: "sin teléfono",
    detail: "Mensaje masivo",
    recipientList: "Destinatarios",
    ok: "enviado",
    notOk: "fallido",
    plannerTitle: "Recordatorios",
    plannerSubtitle: "Los envíos pasan por la pareja. Presenta una solicitud de recordatorio y ellos la aprueban.",
    plannerRequest: "Pedir a la pareja que envíe recordatorios",
    plannerAudiences: "A quién se podría llegar",
    plannerPhones: "{with}, {without} sin teléfono",
    plannerWithPhone: { one: "{n} invitado con teléfono", other: "{n} invitados con teléfono" },
    tabTitle: "Avisos",
    tabSubtitle: "Mensajes de WhatsApp a tus invitados, con plantillas aprobadas para tu boda.",
    notReadyTitle: "Los avisos todavía no están listos",
    notReadyBody: "WhatsApp solo te deja escribirles a tus invitados con plantillas que aprobó para tu boda, y la tuya todavía no tiene. Pide una y el equipo de Guest-ly la lleva a WhatsApp por ti.",
    notReadyBodyNoRequest: "WhatsApp solo te deja escribirles a tus invitados con plantillas que aprobó para tu boda, y la tuya todavía no tiene. Escríbele a Guest-ly para preparar una.",
    yourTemplates: "Tus plantillas",
    templatesEmpty: "Todavía no tienes plantillas aprobadas.",
    langNames: { en: "inglés", es: "español" },
    demo: "Demo",
    demoNote: "Boda demo: los mensajes no se entregan.",
    demoSent: "Boda demo: quedó registrado, no se entregó nada.",
    requestTemplate: "Pedir una plantilla",
    requestTemplateSub: "Un nuevo tipo de mensaje, revisado por WhatsApp",
    requestLimit: "Tienes 3 solicitudes en curso. Espera a que termine una o cancela una.",
    yourRequests: "Tus solicitudes",
    status: {
      submitted: "Enviada",
      in_review: "En revisión",
      needs_info: "Falta info",
      with_whatsapp: "En WhatsApp",
      approved: "Aprobada",
      rejected: "Rechazada",
      cancelled: "Cancelada",
    },
    kinds: {
      rsvp_closing: "Cierre de RSVP",
      transport: "Transporte",
      thank_you: "Agradecimiento",
      schedule_change: "Cambio de horario",
      welcome: "Bienvenida",
      meal_choice: "Elección de menú",
      other: "Otra cosa",
    },
    teamNote: "Nota de Guest-ly",
    formTitle: "Pedir una plantilla",
    formEditTitle: "Edita tu solicitud",
    formLead: "El equipo de Guest-ly la revisa y la lleva a WhatsApp para que la apruebe. Nada les llega a tus invitados hasta que esté aprobada y tú la envíes.",
    formKind: "Para qué es",
    formName: "Ponle nombre",
    formNamePlaceholder: "Por ejemplo: Horarios del transporte",
    formPurpose: "Qué debe decir",
    formPurposePlaceholder: "Lo que tus invitados necesitan saber, y por qué",
    formWhen: "Cuándo la enviarías",
    formWhenPlaceholder: "Por ejemplo: la semana antes de la boda",
    formLanguages: "Idiomas",
    formDraftEn: "Borrador en inglés (opcional)",
    formDraftEs: "Borrador en español (opcional)",
    formDraftPlaceholder: "Tu redacción, si ya tienes una en mente",
    formSend: "Enviar solicitud",
    formSave: "Guardar cambios",
    formMissing: "Agrega un nombre y lo que debe decir.",
    formLangMissing: "Elige al menos un idioma.",
    formSent: "Solicitud enviada. Te avisamos cuando avance.",
    formSaved: "Solicitud actualizada.",
    formFailed: "No se pudo enviar la solicitud. Intenta otra vez.",
    requestEdit: "Editar solicitud",
    requestCancel: "Cancelar solicitud",
    requestCancelTitle: "¿Cancelar esta solicitud?",
    requestCancelBody: "El equipo de Guest-ly deja de trabajar en ella. Puedes mandar una nueva cuando quieras.",
    requestKeep: "Conservarla",
    requestCancelled: "Solicitud cancelada.",
    requestSentOn: "Enviada {when}",
    requestUpdated: "Actualizada {when}",
    close: "Cerrar",
    templateMissing: "Tu plantilla de {name} todavía no está lista",
    templateMissingBody: "Primero WhatsApp tiene que aprobarla para tu boda. Pídela y te avisamos cuando esté lista.",
    templateChanged: "Esta plantilla cambió. Revísala otra vez antes de enviar.",
    oneLanguage: "Esta plantilla solo está en {lang}. Todos tus invitados la reciben en {lang}.",
    plannerTabTitle: "Avisos",
    plannerTabSubtitle: "La pareja envía los mensajes de WhatsApp. Aquí ves sus plantillas, puedes pedirles que envíen y pedir una plantilla nueva.",
    plannerAsk: "Pedir a la pareja que envíe",
    plannerTemplatesNote: "Solo la pareja puede enviarlas.",
    plannerTemplates: "Plantillas de la pareja",
    plannerNotReady: "WhatsApp solo deja que la pareja les escriba a sus invitados con plantillas que aprobó para esta boda, y todavía no tiene ninguna. Pide una y el equipo de Guest-ly la lleva a WhatsApp.",
  },
};
