// Budget copy, EN and neutral LatAm ES (usted).

const en = {
  title: "Budget",
  subtitle: "Every line, every payment, one total.",
  pending: "The budget is still being set up for this wedding. Nothing is lost, check back shortly.",
  readOnly: "You can view the budget but not change it.",
  emptyTitle: "No budget yet",
  emptyBody: "Start with a name and a currency, or read one out of a spreadsheet or a photo.",
  createBudget: "Create budget",
  importBudget: "Import from file or photo",
  settings: "Budget settings",
  name: "Budget name",
  currency: "Currency (3 letters)",
  altCurrency: "Second currency (optional)",
  fxRate: "Rate: 1 second currency = ? base",
  guestCount: "Guest count",
  notes: "Notes",
  total: "Total",
  paid: "Paid",
  planned: "Scheduled",
  remaining: "Remaining",
  perGuest: "per guest",
  unpriced: "{n} lines still without a price",
  foreign: "Some lines use a currency this budget cannot convert.",
  categories: "Categories",
  uncategorized: "No category",
  addCategory: "Add category",
  categoryName: "Category name",
  renameCategory: "Rename category",
  deleteCategory: "Delete category",
  deleteCategoryBody: "Lines in it stay in the budget without a category.",
  items: "Lines",
  addItem: "Add line",
  addSubItem: "Add a line inside",
  itemTitle: "What is it",
  vendor: "Vendor",
  qty: "Quantity",
  unitPrice: "Unit price",
  unitLabel: "Unit (e.g. person, hour)",
  amountOverride: "Fixed total (overrides quantity x price)",
  note: "Note",
  status: "Status",
  statuses: { quoted: "Quoted", confirmed: "Confirmed", pending: "Pending", cancelled: "Cancelled" } as Record<string, string>,
  noPrice: "No price yet",
  subtotal: "Subtotal",
  moveUp: "Move up",
  moveDown: "Move down",
  payments: "Payments",
  addPayment: "Add payment",
  amount: "Amount",
  paidOn: "Date (YYYY-MM-DD)",
  kind: "Type",
  kinds: { paid: "Paid", planned: "Scheduled" } as Record<string, string>,
  method: "Method (transfer, cash, card)",
  paidBy: "Paid by",
  reimbursable: "Reimbursable",
  noPayments: "No payments recorded yet.",
  comments: "Comments",
  commentPlaceholder: "Write a comment",
  send: "Send",
  deleteItem: "Delete line",
  deleteItemBody: "Its payments and comments go with it.",
  deletePayment: "Remove payment",
  archive: "Archive this budget",
  archiveBody: "It disappears from the app and the web. Nothing is deleted.",
  months: "Upcoming months",
  save: "Save",
  cancel: "Cancel",
  delete: "Delete",
  confirm: "Confirm",
  saved: "Saved",
  offline: "You are offline. Changes need a connection.",
  switchBudget: "Budgets",
  linkedVendor: "Linked vendor",
  importTitle: "Read a budget",
  importIntro: "Paste a list, choose a spreadsheet, or take a photo of a printed one. You review every line before anything is saved.",
  paste: "Paste text",
  pastePlaceholder: "Item, vendor, amount, one per line",
  takePhoto: "Take a photo",
  choosePhoto: "Choose a photo",
  chooseFile: "Choose a spreadsheet",
  reading: "Reading",
  read: "Read it",
  previewTitle: "Review what was read",
  previewBody: "Fix titles or amounts, remove lines you do not want, then confirm.",
  warnings: "Notes from the reader",
  target: "Where does it go",
  newBudget: "A new budget",
  intoExisting: "Into {name}",
  commit: "Save {n} lines",
  imported: "{items} lines and {payments} payments saved.",
  removeLine: "Remove",
  nothingRead: "Nothing could be read from that.",
  permission: "Camera or photo access was not granted.",
};

const es: typeof en = {
  title: "Presupuesto",
  subtitle: "Cada línea, cada pago, un solo total.",
  pending: "El presupuesto todavía se está preparando para esta boda. No se pierde nada, vuelva a intentarlo en un momento.",
  readOnly: "Puede ver el presupuesto pero no modificarlo.",
  emptyTitle: "Todavía no hay presupuesto",
  emptyBody: "Empiece con un nombre y una moneda, o léalo desde una hoja de cálculo o una foto.",
  createBudget: "Crear presupuesto",
  importBudget: "Importar desde archivo o foto",
  settings: "Ajustes del presupuesto",
  name: "Nombre del presupuesto",
  currency: "Moneda (3 letras)",
  altCurrency: "Segunda moneda (opcional)",
  fxRate: "Tipo de cambio: 1 segunda moneda = ? base",
  guestCount: "Cantidad de invitados",
  notes: "Notas",
  total: "Total",
  paid: "Pagado",
  planned: "Programado",
  remaining: "Restante",
  perGuest: "por invitado",
  unpriced: "{n} líneas todavía sin precio",
  foreign: "Algunas líneas usan una moneda que este presupuesto no puede convertir.",
  categories: "Categorías",
  uncategorized: "Sin categoría",
  addCategory: "Agregar categoría",
  categoryName: "Nombre de la categoría",
  renameCategory: "Renombrar categoría",
  deleteCategory: "Eliminar categoría",
  deleteCategoryBody: "Sus líneas quedan en el presupuesto sin categoría.",
  items: "Líneas",
  addItem: "Agregar línea",
  addSubItem: "Agregar una línea dentro",
  itemTitle: "Qué es",
  vendor: "Proveedor",
  qty: "Cantidad",
  unitPrice: "Precio unitario",
  unitLabel: "Unidad (p. ej. persona, hora)",
  amountOverride: "Total fijo (reemplaza cantidad x precio)",
  note: "Nota",
  status: "Estado",
  statuses: { quoted: "Cotizado", confirmed: "Confirmado", pending: "Pendiente", cancelled: "Cancelado" },
  noPrice: "Todavía sin precio",
  subtotal: "Subtotal",
  moveUp: "Subir",
  moveDown: "Bajar",
  payments: "Pagos",
  addPayment: "Agregar pago",
  amount: "Monto",
  paidOn: "Fecha (AAAA-MM-DD)",
  kind: "Tipo",
  kinds: { paid: "Pagado", planned: "Programado" },
  method: "Método (transferencia, efectivo, tarjeta)",
  paidBy: "Pagado por",
  reimbursable: "Reembolsable",
  noPayments: "Todavía no hay pagos registrados.",
  comments: "Comentarios",
  commentPlaceholder: "Escriba un comentario",
  send: "Enviar",
  deleteItem: "Eliminar línea",
  deleteItemBody: "Sus pagos y comentarios se eliminan con ella.",
  deletePayment: "Quitar pago",
  archive: "Archivar este presupuesto",
  archiveBody: "Desaparece de la app y de la web. No se elimina nada.",
  months: "Próximos meses",
  save: "Guardar",
  cancel: "Cancelar",
  delete: "Eliminar",
  confirm: "Confirmar",
  saved: "Guardado",
  offline: "Está sin conexión. Los cambios necesitan conexión.",
  switchBudget: "Presupuestos",
  linkedVendor: "Proveedor vinculado",
  importTitle: "Leer un presupuesto",
  importIntro: "Pegue una lista, elija una hoja de cálculo o tome una foto de una impresa. Usted revisa cada línea antes de que se guarde algo.",
  paste: "Pegar texto",
  pastePlaceholder: "Concepto, proveedor, monto, uno por línea",
  takePhoto: "Tomar una foto",
  choosePhoto: "Elegir una foto",
  chooseFile: "Elegir una hoja de cálculo",
  reading: "Leyendo",
  read: "Leer",
  previewTitle: "Revise lo que se leyó",
  previewBody: "Corrija títulos o montos, quite las líneas que no quiera y confirme.",
  warnings: "Notas del lector",
  target: "Dónde se guarda",
  newBudget: "Un presupuesto nuevo",
  intoExisting: "Dentro de {name}",
  commit: "Guardar {n} líneas",
  imported: "Se guardaron {items} líneas y {payments} pagos.",
  removeLine: "Quitar",
  nothingRead: "No se pudo leer nada de eso.",
  permission: "No se concedió acceso a la cámara o a las fotos.",
};

export const COPY = { en, es };
export type BudgetCopy = typeof en;
