// Welcome tour copy, both languages. Short and warm; every step names the
// real place in the app where the feature lives, with the app's own labels.
// No emojis, no em dashes. Spanish uses tú, Latin American neutral.

type Step = {
  title: string;
  /** Used when the name it interpolates is unknown. */
  titleNoName?: string;
  body: string;
  bodyNoName?: string;
  /** "Find it" line: where the feature lives. */
  where?: string;
  /** "How to use it best" line. */
  tip?: string;
  /** Visible nudge on a tap-to-try scene. */
  tryIt?: string;
  /** What the illustration shows, for VoiceOver. */
  scene: string;
};

const en = {
  a11yTitle: "Welcome tour",
  skip: "Skip",
  skipLabel: "Skip the tour",
  next: "Next",
  back: "Back",
  stepOf: "Step {n} of {total}",
  findIt: "Find it",
  tip: "Best tip",
  tryHint: "Double tap to try it.",
  swipeDown: "Swipe down to close",
  replay: "Take the tour",
  replayDetail: "A quick look at the best parts",
  steps: {
    // Build 12: at most three cards per tour, each naming a real tab. The
    // last card closes the tour (no separate celebration card).
    guest: {
      rsvp: {
        title: "Answer for your whole party.",
        body: "Your Invitation tab opens on your reply. Mark each person for each event and change it any time until the deadline.",
        where: "Invitation tab, Answer now",
        tip: "Answer early: the couple plans seats and menus around it.",
        tryIt: "Tap a card to answer",
        scene: "Two RSVP cards, one for you and one for a party member. Tapping one marks that person as attending.",
      },
      calendar: {
        title: "Never miss a moment.",
        body: "Schedule has every event you are invited to, in local time. Add them to your calendar in one tap.",
        where: "Schedule tab",
        tip: "Adding it gives you a reminder the day before.",
        tryIt: "Tap Add to calendar",
        scene: "An event card with an Add to calendar button. Tapping it drops the event into a calendar.",
      },
      concierge: {
        title: "Ask anything, any hour.",
        body: "The concierge is an AI assistant that knows this wedding: schedule, venues, hotels, gifts and dress code. If it cannot answer, it asks the couple and their reply lands in the same chat.",
        where: "Ask tab",
        tip: "Replay this tour any time from Info.",
        tryIt: "Tap a question",
        scene: "A chat with the concierge. Tapping a suggested question shows its answer.",
      },
    },
    couple: {
      home: {
        title: "Start each day on Home.",
        body: "See who has answered at a glance. Reminders lists only what needs you, like a guest question or a planner request.",
        where: "Home tab, Reminders",
        tip: "Tap a line to jump straight to it. Handle it and the list gets shorter.",
        tryIt: "Tap a line to handle it",
        scene: "A list of three reminders. Tapping a line marks it handled.",
      },
      guests: {
        title: "Guests and answers, together.",
        body: "Guests holds the whole list with every RSVP, live. Tap a name to edit the guest or their answer.",
        where: "Guests tab",
        tip: "Send reminder, top right, nudges everyone who has not answered.",
        tryIt: "Tap Record an RSVP",
        scene: "RSVP counters and a list of answers. Tapping Record an RSVP adds an answer received in person.",
      },
      tools: {
        title: "Plan it, with help.",
        body: "Tools holds your wedding site, Budget, Tasks, Seating and the Day-of schedule. Your Coordinator reads your wedding and proposes; nothing changes until you tap Confirm.",
        where: "Tools tab, and the gold button on any screen",
        tip: "Replay this tour any time in Settings.",
        tryIt: "Tap Confirm",
        scene: "A chat with the Coordinator proposing a change. Tapping Confirm applies it.",
      },
    },
    pending: {
      intro: {
        title: "Almost ready.",
        body: "Your wedding is being set up. Here is a quick look at what opens up the moment your account is active.",
        scene: "A gold gem taking shape.",
      },
    },
    planner: {
      weddings: {
        title: "Every wedding, one tap apart.",
        body: "The pill at the top of every tab shows the wedding you are in. Tap it to switch; every tab follows.",
        where: "The pill at the top left, on every tab",
        tip: "Weddings with open requests show a count. Start there.",
        tryIt: "Tap a wedding",
        scene: "A list of three weddings. Tapping one makes it the current wedding.",
      },
      propose: {
        title: "You propose. The couple approves.",
        body: "To do holds your tasks and your requests to the couple. Need seats or a guest fixed? Send a request; once approved, the change applies itself.",
        where: "To do tab, or New request on Today",
        tip: "Add a short note for the couple. Clear requests get answered faster.",
        tryIt: "Tap Send",
        scene: "A request to add a seat. Tapping Send sends it to the couple, who approve it.",
      },
      tools: {
        title: "Every tool, one tab.",
        body: "Tools has what the couple shares with you: {tools}.",
        bodyNoName: "The Tools tab shows what the couple shares with you. A locked tile lets you ask them for access.",
        where: "Tools tab",
        tip: "Replay this tour any time in Settings.",
        scene: "Four tool tiles. The ones the couple shares with you are lit; the others show a lock.",
      },
      coordinator: "Your Coordinator can file requests for you too: tap the gold button on any screen.",
    },
  },
  cta: {
    guest: "Open my invitation",
    couple: "Go to my wedding",
    pending: "Got it",
    planner: "Go to my weddings",
  },
  // Sample content drawn inside the illustrations.
  demo: {
    ceremony: "Ceremony",
    reception: "Reception",
    ceremonyTime: "Ceremony · 4:00 PM",
    garden: "The garden",
    tapToAnswer: "Tap to answer",
    hello: "Hello! Ask me anything about the wedding.",
    day: "21",
    added: "Added",
    q1: "What is the dress code?",
    a1: "Formal. Think garden chic, and bring comfortable shoes for the lawn.",
    q2: "Hotels nearby?",
    a2: "Casa Azul holds a room block for guests, five minutes from the venue.",
    q3: "Is there a gift registry?",
    a3: "Yes. The registry is in More, Gifts, with a link to each store.",
    headTo: "Ceremony, the garden",
    inMinutes: "Starts in 25 min",
    shuttleAt: "Shuttle leaves 3:30 PM",
    brief1: "3 guests asked about parking",
    brief2: "Lucía changed her answer",
    brief3: "Your planner sent a request",
    handled: "Handled",
    newAnswer: "Aunt Carmen",
    inPerson: "In person",
    guestName: "Mateo R.",
    guestQ: "Can we bring our baby to the reception?",
    coupleA: "Of course! There is a quiet room next to the hall.",
    askWho: "Add Aunt Carmen and her husband.",
    coordA: "Ready. Confirm and I will add them to your list.",
    cardTitle: "Add a guest",
    cardSub: "Aunt Carmen · Party of 2",
    passName: "Sofía & Diego",
    partyOf2: "Party of 2",
    wedding1: "Camila & Andrés",
    wedding2: "Lucía & Tomás",
    wedding3: "Valeria & Nico",
    inDays: "In {n} days",
    reqTitle: "Add a seat for Mateo R.",
    reqNote: "His partner confirmed by phone.",
    send: "Send",
    reqA: "Edit a guest · Ana P.",
    reqB: "Record an RSVP · the Ruiz family",
    reqC: "Add seats · Mateo R.",
    coupleSays: "Approved, thanks!",
    declinedWhy: "We already have her new number, thanks!",
    lucia: "Lucía M.",
    ana: "Ana P.",
    task: "Confirm the florist",
    colOpen: "Open",
    colDoing: "In progress",
    colDone: "Done",
  },
};

export type TourCopy = typeof en;
export type TourStepCopy = Step;

const es: TourCopy = {
  a11yTitle: "Recorrido de bienvenida",
  skip: "Omitir",
  skipLabel: "Omitir el recorrido",
  next: "Siguiente",
  back: "Atrás",
  stepOf: "Paso {n} de {total}",
  findIt: "Dónde está",
  tip: "El mejor consejo",
  tryHint: "Toca dos veces para probarlo.",
  swipeDown: "Desliza hacia abajo para cerrar",
  replay: "Ver el recorrido",
  replayDetail: "Un vistazo rápido a lo mejor de la app",
  steps: {
    guest: {
      rsvp: {
        title: "Responde por todo tu grupo.",
        body: "Tu pestaña Invitación abre con tu respuesta. Marca a cada persona en cada evento y cámbiala cuando quieras hasta la fecha límite.",
        where: "Pestaña Invitación, Responder ahora",
        tip: "Responde pronto: la pareja organiza mesas y menú con tu respuesta.",
        tryIt: "Toca una tarjeta para responder",
        scene: "Dos tarjetas de confirmación, una para ti y otra para un acompañante. Al tocar una, esa persona queda como que asistirá.",
      },
      calendar: {
        title: "No te pierdas ningún momento.",
        body: "En Programa está cada evento al que estás invitado, en hora local. Agrégalos a tu calendario con un toque.",
        where: "Pestaña Programa",
        tip: "Al agregarlo recibes un recordatorio el día anterior.",
        tryIt: "Toca Agregar al calendario",
        scene: "Una tarjeta de evento con el botón Agregar al calendario. Al tocarlo, el evento entra al calendario.",
      },
      concierge: {
        title: "Pregunta lo que quieras, a cualquier hora.",
        body: "El concierge es un asistente de IA que conoce esta boda: programa, lugares, hoteles, regalos y vestimenta. Si no sabe algo, le pregunta a la pareja y su respuesta llega al mismo chat.",
        where: "Pestaña Preguntar",
        tip: "Puedes repetir este recorrido cuando quieras desde Info.",
        tryIt: "Toca una pregunta",
        scene: "Un chat con el concierge. Al tocar una pregunta sugerida aparece su respuesta.",
      },
    },
    couple: {
      home: {
        title: "Empieza cada día en Inicio.",
        body: "Ve de un vistazo quién ya respondió. Recordatorios muestra solo lo que te necesita, como la pregunta de un invitado o una solicitud de tu planner.",
        where: "Pestaña Inicio, Recordatorios",
        tip: "Toca una línea para ir directo. Resuélvela y la lista se acorta.",
        tryIt: "Toca una línea para resolverla",
        scene: "Una lista de tres recordatorios. Al tocar una línea, queda resuelta.",
      },
      guests: {
        title: "Invitados y respuestas, juntos.",
        body: "Invitados tiene la lista completa con cada respuesta, en vivo. Toca un nombre para editar al invitado o su respuesta.",
        where: "Pestaña Invitados",
        tip: "Mandar recordatorio, arriba a la derecha, le escribe a todos los que no han respondido.",
        tryIt: "Toca Registrar una respuesta",
        scene: "Contadores de confirmación y una lista de respuestas. Al tocar Registrar una respuesta se agrega una recibida en persona.",
      },
      tools: {
        title: "Planéalo, con ayuda.",
        body: "En Herramientas están tu sitio, Presupuesto, Tareas, Mesas e Itinerario del día. Tu Coordinador lee tu boda y propone; nada cambia hasta que tocas Confirmar.",
        where: "Pestaña Herramientas, y el botón dorado en cualquier pantalla",
        tip: "Puedes repetir este recorrido cuando quieras en Ajustes.",
        tryIt: "Toca Confirmar",
        scene: "Un chat con el Coordinador proponiendo un cambio. Al tocar Confirmar se aplica.",
      },
    },
    pending: {
      intro: {
        title: "Ya casi está.",
        body: "Estamos preparando tu boda. Aquí tienes un vistazo de lo que se abre en cuanto tu cuenta esté activa.",
        scene: "Una gema dorada tomando forma.",
      },
    },
    planner: {
      weddings: {
        title: "Cada boda, a un toque.",
        body: "La píldora arriba de cada pestaña muestra la boda en la que estás. Tócala para cambiar; todas las pestañas la siguen.",
        where: "La píldora arriba a la izquierda, en cada pestaña",
        tip: "Las bodas con solicitudes abiertas muestran un número. Empieza por ahí.",
        tryIt: "Toca una boda",
        scene: "Una lista de tres bodas. Al tocar una, pasa a ser la boda actual.",
      },
      propose: {
        title: "Tú propones. La pareja aprueba.",
        body: "En Pendientes están tus tareas y tus solicitudes a la pareja. ¿Faltan lugares o hay que corregir un invitado? Manda una solicitud; cuando la aprueban, el cambio se aplica solo.",
        where: "Pestaña Pendientes, o Nueva solicitud en Hoy",
        tip: "Agrega una nota breve para la pareja. Las solicitudes claras se responden más rápido.",
        tryIt: "Toca Enviar",
        scene: "Una solicitud para agregar un lugar. Al tocar Enviar llega a la pareja, que la aprueba.",
      },
      tools: {
        title: "Cada herramienta, en una pestaña.",
        body: "Herramientas tiene lo que la pareja comparte contigo: {tools}.",
        bodyNoName: "La pestaña Herramientas muestra lo que la pareja comparte contigo. Desde una tarjeta con candado puedes pedirles acceso.",
        where: "Pestaña Herramientas",
        tip: "Puedes repetir este recorrido cuando quieras en Ajustes.",
        scene: "Cuatro tarjetas de herramientas. Las que la pareja comparte contigo están encendidas; las demás muestran un candado.",
      },
      coordinator: "Tu Coordinador también puede crear solicitudes por ti: toca el botón dorado en cualquier pantalla.",
    },
  },
  cta: {
    guest: "Abrir mi invitación",
    couple: "Ir a mi boda",
    pending: "Entendido",
    planner: "Ir a mis bodas",
  },
  demo: {
    ceremony: "Ceremonia",
    reception: "Recepción",
    ceremonyTime: "Ceremonia · 16:00",
    garden: "El jardín",
    tapToAnswer: "Toca para responder",
    hello: "¡Hola! Pregúntame lo que quieras sobre la boda.",
    day: "21",
    added: "Agregado",
    q1: "¿Cuál es la vestimenta?",
    a1: "Formal. Piensa en elegante de jardín, y trae zapatos cómodos para el césped.",
    q2: "¿Hoteles cerca?",
    a2: "Casa Azul tiene habitaciones reservadas para invitados, a cinco minutos del lugar.",
    q3: "¿Hay mesa de regalos?",
    a3: "Sí. La mesa de regalos está en Más, Regalos, con el enlace a cada tienda.",
    headTo: "Ceremonia, el jardín",
    inMinutes: "Empieza en 25 min",
    shuttleAt: "El transporte sale a las 15:30",
    brief1: "3 invitados preguntaron por el estacionamiento",
    brief2: "Lucía cambió su respuesta",
    brief3: "Tu planner envió una solicitud",
    handled: "Resuelto",
    newAnswer: "Tía Carmen",
    inPerson: "En persona",
    guestName: "Mateo R.",
    guestQ: "¿Podemos llevar a nuestro bebé a la recepción?",
    coupleA: "¡Claro! Hay una sala tranquila junto al salón.",
    askWho: "Agrega a la tía Carmen y a su esposo.",
    coordA: "Listo. Confirma y los agrego a tu lista.",
    cardTitle: "Agregar un invitado",
    cardSub: "Tía Carmen · Grupo de 2",
    passName: "Sofía y Diego",
    partyOf2: "Grupo de 2",
    wedding1: "Camila y Andrés",
    wedding2: "Lucía y Tomás",
    wedding3: "Valeria y Nico",
    inDays: "En {n} días",
    reqTitle: "Agregar un lugar para Mateo R.",
    reqNote: "Su pareja confirmó por teléfono.",
    send: "Enviar",
    reqA: "Editar un invitado · Ana P.",
    reqB: "Registrar una respuesta · familia Ruiz",
    reqC: "Agregar lugares · Mateo R.",
    coupleSays: "¡Aprobada, gracias!",
    declinedWhy: "Ya tenemos su número nuevo, ¡gracias!",
    lucia: "Lucía M.",
    ana: "Ana P.",
    task: "Confirmar la florería",
    colOpen: "Abierta",
    colDoing: "En curso",
    colDone: "Hecha",
  },
};

export const TOUR_COPY = { en, es };
