// Welcome tour copy, both languages. Short and warm; every step names the
// real place in the app where the feature lives, with the app's own labels.
// No emojis, no em dashes. Spanish uses tú, Latin American neutral.

type Step = {
  title: string;
  /** Used when the name it interpolates is unknown. */
  titleNoName?: string;
  body: string;
  bodyNoName?: string;
  /** "Find it" line: where the feature lives. */
  where?: string;
  /** "How to use it best" line. */
  tip?: string;
  /** Visible nudge on a tap-to-try scene. */
  tryIt?: string;
  /** What the illustration shows, for VoiceOver. */
  scene: string;
};

const en = {
  a11yTitle: "Welcome tour",
  skip: "Skip",
  skipLabel: "Skip the tour",
  next: "Next",
  back: "Back",
  stepOf: "Step {n} of {total}",
  findIt: "Find it",
  tip: "Best tip",
  tryHint: "Double tap to try it.",
  swipeDown: "Swipe down to close",
  replay: "Take the tour",
  replayDetail: "A quick look at the best parts",
  steps: {
    guest: {
      rsvp: {
        title: "Answer for your whole party.",
        body: "Mark each person for each event. Changed your plans? Edit it any time until the deadline.",
        where: "RSVP tab, or Answer now on Home",
        tip: "Answer early: the couple plans seats and menus around it.",
        tryIt: "Tap a card to answer",
        scene: "Two RSVP cards, one for you and one for a party member. Tapping one marks that person as attending.",
      },
      calendar: {
        title: "Never miss a moment.",
        body: "Schedule has every event you are invited to, in local time. Add them to your calendar in one tap.",
        where: "Schedule tab, calendar button at the top",
        tip: "Adding it gives you a reminder the day before.",
        tryIt: "Tap Add to calendar",
        scene: "An event card with an Add to calendar button. Tapping it drops the event into a calendar.",
      },
      concierge: {
        title: "Ask anything, any hour.",
        body: "The concierge is an AI assistant that knows this wedding: schedule, venues, hotels, gifts and dress code.",
        where: "Concierge tab",
        tip: "If it cannot answer, it asks the couple. Their reply lands in Messages, the bell on Home.",
        tryIt: "Tap a question",
        scene: "A chat with the concierge. Tapping a suggested question shows its answer.",
      },
      dayof: {
        title: "On the day, just follow Home.",
        body: "From 5:00 on the wedding day, Home shows where to be right now, with directions in Maps and the shuttle.",
        where: "Home, on the wedding day",
        tip: "Allow notifications to hear about any change of time or place.",
        scene: "A map with a route to the ceremony and a card that says where to head right now.",
      },
      ready: {
        title: "You are all set, {name}.",
        titleNoName: "You are all set.",
        body: "Everything about {couple}'s wedding is one tap away.",
        bodyNoName: "Everything about the wedding is one tap away.",
        tip: "Replay this tour any time from More.",
        scene: "A gold gem assembles and bursts into small gems.",
      },
    },
    couple: {
      briefing: {
        title: "Start each day on Home.",
        body: "Today's briefing lists only what needs you right now, from guest questions to planner requests.",
        where: "Home, Today's briefing",
        tip: "Tap a line to jump straight to it. Handle it and the list gets shorter.",
        tryIt: "Tap a line to handle it",
        scene: "Today's briefing with three lines. Tapping a line marks it handled.",
      },
      rsvps: {
        title: "Every answer, live.",
        body: "Guests holds the whole list. RSVPs shows who is coming, who declined and who is still pending, as they answer.",
        where: "Guests and RSVPs tabs",
        tip: "Got a yes in person? RSVPs, Record an RSVP, and it counts right away.",
        tryIt: "Tap Record an RSVP",
        scene: "RSVP counters and a list of answers. Tapping Record an RSVP adds an answer received in person.",
      },
      messages: {
        title: "Only the questions that need you.",
        body: "The concierge answers guests for you. When it cannot, the question waits in Messages under Needs you.",
        where: "Messages tab, Needs you",
        tip: "Reply in the app and the guest gets it as a notification. WhatsApp threads open WhatsApp for you to send.",
        tryIt: "Tap Reply",
        scene: "A guest question waiting for you. Tapping Reply sends your answer.",
      },
      coordinator: {
        title: "Meet your AI Coordinator.",
        body: "Ask who has not answered, add a guest, draft a reminder. It reads your wedding and proposes; nothing changes until you tap Confirm.",
        where: "The gold sparkle button, or More, Coordinator",
        tip: "Drag the gold button anywhere. It remembers where you leave it.",
        tryIt: "Tap Confirm",
        scene: "A chat with the Coordinator proposing a change. Tapping Confirm applies it.",
      },
      checkin: {
        title: "Door check-in, even offline.",
        body: "Scan each guest's pass or type a name. No signal? Check-ins wait on your phone and sync when you are back online.",
        where: "More, Check-in",
        tip: "Day-of mode switches on by itself on the wedding day, with check-in one tap away.",
        tryIt: "Tap to scan",
        scene: "A camera frame scanning a guest pass. Tapping it checks the guest in, even with no connection.",
      },
      ready: {
        title: "Your wedding, handled.",
        body: "Guests, answers and the day itself, in one calm place.",
        tip: "Replay this tour any time in Settings.",
        scene: "A gold gem assembles and bursts into small gems.",
      },
    },
    pending: {
      intro: {
        title: "Almost ready.",
        body: "Your wedding is being set up. Here is a quick look at what opens up the moment your account is active.",
        scene: "A gold gem taking shape.",
      },
      ready: {
        title: "All of this is waiting for you.",
        body: "As soon as your account is active, your wedding opens right here.",
        scene: "A gold gem assembles and bursts into small gems.",
      },
    },
    planner: {
      weddings: {
        title: "Every wedding, one tap apart.",
        body: "Home lists every wedding you plan. Tap one to switch; guests, requests and budget follow.",
        where: "Home, Your weddings, or Settings, Wedding",
        tip: "Weddings with open requests show an amber count. Start there.",
        tryIt: "Tap a wedding",
        scene: "A list of three weddings. Tapping one makes it the current wedding.",
      },
      propose: {
        title: "You propose. The couple approves.",
        body: "Need extra seats or a guest fixed? File a request. Once the couple approves, the change applies itself.",
        where: "Requests tab, the + button",
        tip: "Add a short note for the couple. Clear requests get answered faster.",
        tryIt: "Tap Send",
        scene: "A request to add a seat. Tapping Send sends it to the couple, who approve it.",
      },
      requests: {
        title: "Follow every request.",
        body: "Each request shows Awaiting the couple, Approved or Declined, with its own conversation.",
        where: "Requests tab",
        tip: "Changed your mind? Withdraw a request while it is still waiting.",
        tryIt: "Tap a request",
        scene: "A list of requests with their status. Tapping one opens its conversation.",
      },
      tasks: {
        title: "One board, shared with the couple.",
        body: "Tasks is the board you and the couple both see. Filter by Mine or Couple and move work to Done.",
        where: "More, Tasks",
        tip: "Start the day on Mine to see just your part.",
        tryIt: "Tap a task to move it",
        scene: "A task board with three columns. Tapping the task moves it to the next column.",
      },
      ready: {
        title: "You are ready.",
        body: "The Coordinator can file requests for you too. Tap the gold sparkle button on any screen.",
        tip: "Replay this tour any time in Settings.",
        scene: "A gold gem assembles and bursts into small gems.",
      },
    },
  },
  cta: {
    guest: "Open my invitation",
    couple: "Go to my wedding",
    pending: "Got it",
    planner: "Go to my weddings",
  },
  // Sample content drawn inside the illustrations.
  demo: {
    ceremony: "Ceremony",
    reception: "Reception",
    ceremonyTime: "Ceremony · 4:00 PM",
    garden: "The garden",
    tapToAnswer: "Tap to answer",
    hello: "Hello! Ask me anything about the wedding.",
    day: "21",
    added: "Added",
    q1: "What is the dress code?",
    a1: "Formal. Think garden chic, and bring comfortable shoes for the lawn.",
    q2: "Hotels nearby?",
    a2: "Casa Azul holds a room block for guests, five minutes from the venue.",
    q3: "Is there a gift registry?",
    a3: "Yes. The registry is in More, Gifts, with a link to each store.",
    headTo: "Ceremony, the garden",
    inMinutes: "Starts in 25 min",
    shuttleAt: "Shuttle leaves 3:30 PM",
    brief1: "3 guests asked about parking",
    brief2: "Lucía changed her answer",
    brief3: "Your planner sent a request",
    handled: "Handled",
    newAnswer: "Aunt Carmen",
    inPerson: "In person",
    guestName: "Mateo R.",
    guestQ: "Can we bring our baby to the reception?",
    coupleA: "Of course! There is a quiet room next to the hall.",
    askWho: "Add Aunt Carmen and her husband.",
    coordA: "Ready. Confirm and I will add them to your list.",
    cardTitle: "Add a guest",
    cardSub: "Aunt Carmen · Party of 2",
    passName: "Sofía & Diego",
    partyOf2: "Party of 2",
    wedding1: "Camila & Andrés",
    wedding2: "Lucía & Tomás",
    wedding3: "Valeria & Nico",
    inDays: "In {n} days",
    reqTitle: "Add a seat for Mateo R.",
    reqNote: "His partner confirmed by phone.",
    send: "Send",
    reqA: "Edit a guest · Ana P.",
    reqB: "Record an RSVP · the Ruiz family",
    reqC: "Add seats · Mateo R.",
    coupleSays: "Approved, thanks!",
    declinedWhy: "We already have her new number, thanks!",
    lucia: "Lucía M.",
    ana: "Ana P.",
    task: "Confirm the florist",
    colOpen: "Open",
    colDoing: "In progress",
    colDone: "Done",
  },
};

export type TourCopy = typeof en;
export type TourStepCopy = Step;

const es: TourCopy = {
  a11yTitle: "Recorrido de bienvenida",
  skip: "Omitir",
  skipLabel: "Omitir el recorrido",
  next: "Siguiente",
  back: "Atrás",
  stepOf: "Paso {n} de {total}",
  findIt: "Dónde está",
  tip: "El mejor consejo",
  tryHint: "Toca dos veces para probarlo.",
  swipeDown: "Desliza hacia abajo para cerrar",
  replay: "Ver el recorrido",
  replayDetail: "Un vistazo rápido a lo mejor de la app",
  steps: {
    guest: {
      rsvp: {
        title: "Responde por todo tu grupo.",
        body: "Marca a cada persona en cada evento. ¿Cambiaste de planes? Puedes editarlo hasta la fecha límite.",
        where: "Pestaña RSVP, o Responder ahora en Inicio",
        tip: "Responde pronto: la pareja organiza mesas y menú con tu respuesta.",
        tryIt: "Toca una tarjeta para responder",
        scene: "Dos tarjetas de confirmación, una para ti y otra para un acompañante. Al tocar una, esa persona queda como que asistirá.",
      },
      calendar: {
        title: "No te pierdas ningún momento.",
        body: "En Programa está cada evento al que estás invitado, en hora local. Agrégalos a tu calendario con un toque.",
        where: "Pestaña Programa, botón de calendario arriba",
        tip: "Al agregarlo recibes un recordatorio el día anterior.",
        tryIt: "Toca Agregar al calendario",
        scene: "Una tarjeta de evento con el botón Agregar al calendario. Al tocarlo, el evento entra al calendario.",
      },
      concierge: {
        title: "Pregunta lo que quieras, a cualquier hora.",
        body: "El concierge es un asistente de IA que conoce esta boda: programa, lugares, hoteles, regalos y vestimenta.",
        where: "Pestaña Concierge",
        tip: "Si no sabe algo, le pregunta a la pareja. Su respuesta llega a Mensajes, la campana en Inicio.",
        tryIt: "Toca una pregunta",
        scene: "Un chat con el concierge. Al tocar una pregunta sugerida aparece su respuesta.",
      },
      dayof: {
        title: "El día de la boda, solo sigue Inicio.",
        body: "Desde las 5:00 del día de la boda, Inicio te muestra dónde estar ahora mismo, con cómo llegar en Mapas y el transporte.",
        where: "Inicio, el día de la boda",
        tip: "Activa las notificaciones para enterarte de cualquier cambio de hora o lugar.",
        scene: "Un mapa con la ruta a la ceremonia y una tarjeta que dice a dónde ir ahora mismo.",
      },
      ready: {
        title: "Todo listo, {name}.",
        titleNoName: "Todo listo.",
        body: "Todo sobre la boda de {couple} está a un toque.",
        bodyNoName: "Todo sobre la boda está a un toque.",
        tip: "Puedes repetir este recorrido cuando quieras desde Más.",
        scene: "Una gema dorada toma forma y estalla en gemas pequeñas.",
      },
    },
    couple: {
      briefing: {
        title: "Empieza cada día en Inicio.",
        body: "El Resumen de hoy muestra solo lo que te necesita ahora, desde preguntas de invitados hasta solicitudes de tu planner.",
        where: "Inicio, Resumen de hoy",
        tip: "Toca una línea para ir directo. Resuélvela y la lista se acorta.",
        tryIt: "Toca una línea para resolverla",
        scene: "El Resumen de hoy con tres líneas. Al tocar una, queda resuelta.",
      },
      rsvps: {
        title: "Cada respuesta, en vivo.",
        body: "Invitados tiene la lista completa. RSVPs muestra quién viene, quién no y quién sigue pendiente, a medida que responden.",
        where: "Pestañas Invitados y RSVPs",
        tip: "¿Te confirmaron en persona? RSVPs, Registrar una respuesta, y cuenta al instante.",
        tryIt: "Toca Registrar una respuesta",
        scene: "Contadores de confirmación y una lista de respuestas. Al tocar Registrar una respuesta se agrega una recibida en persona.",
      },
      messages: {
        title: "Solo las preguntas que te necesitan.",
        body: "El concierge responde a los invitados por ti. Cuando no puede, la pregunta te espera en Mensajes, en Te necesitan.",
        where: "Pestaña Mensajes, Te necesitan",
        tip: "Responde en la app y el invitado la recibe como notificación. Los chats de WhatsApp abren WhatsApp para que la envíes tú.",
        tryIt: "Toca Responder",
        scene: "Una pregunta de un invitado esperándote. Al tocar Responder se envía tu respuesta.",
      },
      coordinator: {
        title: "Conoce a tu Coordinador de IA.",
        body: "Pregúntale quién no ha respondido, agrega un invitado, prepara un recordatorio. Lee tu boda y propone; nada cambia hasta que tocas Confirmar.",
        where: "El botón dorado con destellos, o Más, Coordinador",
        tip: "Arrastra el botón dorado a donde quieras. Recuerda dónde lo dejas.",
        tryIt: "Toca Confirmar",
        scene: "Un chat con el Coordinador proponiendo un cambio. Al tocar Confirmar se aplica.",
      },
      checkin: {
        title: "Check-in en la puerta, incluso sin conexión.",
        body: "Escanea el pase de cada invitado o escribe un nombre. ¿Sin señal? Los registros esperan en tu teléfono y se sincronizan al volver la conexión.",
        where: "Más, Check-in",
        tip: "El modo del día se activa solo el día de la boda, con el check-in a un toque.",
        tryIt: "Toca para escanear",
        scene: "Una cámara escaneando el pase de un invitado. Al tocarla, el invitado queda registrado, incluso sin conexión.",
      },
      ready: {
        title: "Tu boda, bajo control.",
        body: "Invitados, respuestas y el gran día, en un solo lugar tranquilo.",
        tip: "Puedes repetir este recorrido cuando quieras en Ajustes.",
        scene: "Una gema dorada toma forma y estalla en gemas pequeñas.",
      },
    },
    pending: {
      intro: {
        title: "Ya casi está.",
        body: "Estamos preparando tu boda. Aquí tienes un vistazo de lo que se abre en cuanto tu cuenta esté activa.",
        scene: "Una gema dorada tomando forma.",
      },
      ready: {
        title: "Todo esto te está esperando.",
        body: "En cuanto tu cuenta esté activa, tu boda se abre aquí mismo.",
        scene: "Una gema dorada toma forma y estalla en gemas pequeñas.",
      },
    },
    planner: {
      weddings: {
        title: "Cada boda, a un toque.",
        body: "Inicio muestra cada boda que planificas. Toca una para cambiar; invitados, solicitudes y presupuesto la siguen.",
        where: "Inicio, Tus bodas, o Ajustes, Boda",
        tip: "Las bodas con solicitudes abiertas muestran un número ámbar. Empieza por ahí.",
        tryIt: "Toca una boda",
        scene: "Una lista de tres bodas. Al tocar una, pasa a ser la boda actual.",
      },
      propose: {
        title: "Tú propones. La pareja aprueba.",
        body: "¿Faltan lugares o hay que corregir un invitado? Crea una solicitud. Cuando la pareja la aprueba, el cambio se aplica solo.",
        where: "Pestaña Solicitudes, el botón +",
        tip: "Agrega una nota breve para la pareja. Las solicitudes claras se responden más rápido.",
        tryIt: "Toca Enviar",
        scene: "Una solicitud para agregar un lugar. Al tocar Enviar llega a la pareja, que la aprueba.",
      },
      requests: {
        title: "Sigue cada solicitud.",
        body: "Cada solicitud muestra Esperando a la pareja, Aprobada o Rechazada, con su propia conversación.",
        where: "Pestaña Solicitudes",
        tip: "¿Cambiaste de idea? Retira una solicitud mientras siga esperando.",
        tryIt: "Toca una solicitud",
        scene: "Una lista de solicitudes con su estado. Al tocar una se abre su conversación.",
      },
      tasks: {
        title: "Un tablero, compartido con la pareja.",
        body: "Tareas es el tablero que ven tú y la pareja. Filtra por Mías o Pareja y lleva el trabajo a Hecha.",
        where: "Más, Tareas",
        tip: "Empieza el día en Mías para ver solo tu parte.",
        tryIt: "Toca una tarea para moverla",
        scene: "Un tablero de tareas con tres columnas. Al tocar la tarea pasa a la siguiente columna.",
      },
      ready: {
        title: "Todo listo.",
        body: "El Coordinador también puede crear solicitudes por ti. Toca el botón dorado con destellos en cualquier pantalla.",
        tip: "Puedes repetir este recorrido cuando quieras en Ajustes.",
        scene: "Una gema dorada toma forma y estalla en gemas pequeñas.",
      },
    },
  },
  cta: {
    guest: "Abrir mi invitación",
    couple: "Ir a mi boda",
    pending: "Entendido",
    planner: "Ir a mis bodas",
  },
  demo: {
    ceremony: "Ceremonia",
    reception: "Recepción",
    ceremonyTime: "Ceremonia · 16:00",
    garden: "El jardín",
    tapToAnswer: "Toca para responder",
    hello: "¡Hola! Pregúntame lo que quieras sobre la boda.",
    day: "21",
    added: "Agregado",
    q1: "¿Cuál es la vestimenta?",
    a1: "Formal. Piensa en elegante de jardín, y trae zapatos cómodos para el césped.",
    q2: "¿Hoteles cerca?",
    a2: "Casa Azul tiene habitaciones reservadas para invitados, a cinco minutos del lugar.",
    q3: "¿Hay mesa de regalos?",
    a3: "Sí. La mesa de regalos está en Más, Regalos, con el enlace a cada tienda.",
    headTo: "Ceremonia, el jardín",
    inMinutes: "Empieza en 25 min",
    shuttleAt: "El transporte sale a las 15:30",
    brief1: "3 invitados preguntaron por el estacionamiento",
    brief2: "Lucía cambió su respuesta",
    brief3: "Tu planner envió una solicitud",
    handled: "Resuelto",
    newAnswer: "Tía Carmen",
    inPerson: "En persona",
    guestName: "Mateo R.",
    guestQ: "¿Podemos llevar a nuestro bebé a la recepción?",
    coupleA: "¡Claro! Hay una sala tranquila junto al salón.",
    askWho: "Agrega a la tía Carmen y a su esposo.",
    coordA: "Listo. Confirma y los agrego a tu lista.",
    cardTitle: "Agregar un invitado",
    cardSub: "Tía Carmen · Grupo de 2",
    passName: "Sofía y Diego",
    partyOf2: "Grupo de 2",
    wedding1: "Camila y Andrés",
    wedding2: "Lucía y Tomás",
    wedding3: "Valeria y Nico",
    inDays: "En {n} días",
    reqTitle: "Agregar un lugar para Mateo R.",
    reqNote: "Su pareja confirmó por teléfono.",
    send: "Enviar",
    reqA: "Editar un invitado · Ana P.",
    reqB: "Registrar una respuesta · familia Ruiz",
    reqC: "Agregar lugares · Mateo R.",
    coupleSays: "¡Aprobada, gracias!",
    declinedWhy: "Ya tenemos su número nuevo, ¡gracias!",
    lucia: "Lucía M.",
    ana: "Ana P.",
    task: "Confirmar la florería",
    colOpen: "Abierta",
    colDoing: "En curso",
    colDone: "Hecha",
  },
};

export const TOUR_COPY = { en, es };
