export const COPY = {
  en: {
    title: "Import guests",
    subtitle: "Paste a list or pick a spreadsheet. Nothing is saved until you confirm.",
    paste: "Paste a list",
    pasteHint: "One guest per line. Name first, phone anywhere. A header row is fine.",
    pastePlaceholder: "María Pérez, +591 7000 0000\nJuan y Ana López, 2",
    pickFile: "Choose a file",
    fileHint: ".csv or .xlsx, up to 8 MB. Zola, The Knot and plain spreadsheets are recognized.",
    parse: "Read the list",
    reading: "Reading",
    preview: "Found {n} guests",
    previewSkipped: "{n} rows skipped",
    duplicates: "{n} already on your list (unchecked)",
    truncated: "Only the first 500 rows are shown.",
    mapping: "Columns read as",
    keep: "Keep",
    party: "{n} people",
    rsvp: "RSVP",
    alreadyOnList: "already on the list",
    import: "Import {n} guests",
    importing: "Importing",
    nothingKept: "Keep at least one guest.",
    doneTitle: "Imported",
    doneBody: "{guests} guests added. {rsvps} RSVP answers recorded.",
    done: "See the list",
    startOver: "Start over",
    error: "Could not read that.",
    noPhone: "no phone",
  },
  es: {
    title: "Importar invitados",
    subtitle: "Pegue una lista o elija una hoja de cálculo. No se guarda nada hasta que confirme.",
    paste: "Pegar una lista",
    pasteHint: "Un invitado por línea. Primero el nombre, el teléfono en cualquier lugar. Puede incluir encabezado.",
    pastePlaceholder: "María Pérez, +591 7000 0000\nJuan y Ana López, 2",
    pickFile: "Elegir un archivo",
    fileHint: ".csv o .xlsx, hasta 8 MB. Se reconocen Zola, The Knot y hojas simples.",
    parse: "Leer la lista",
    reading: "Leyendo",
    preview: "Se encontraron {n} invitados",
    previewSkipped: "{n} filas omitidas",
    duplicates: "{n} ya están en su lista (sin marcar)",
    truncated: "Solo se muestran las primeras 500 filas.",
    mapping: "Columnas leídas como",
    keep: "Conservar",
    party: "{n} personas",
    rsvp: "RSVP",
    alreadyOnList: "ya está en la lista",
    import: "Importar {n} invitados",
    importing: "Importando",
    nothingKept: "Conserve al menos un invitado.",
    doneTitle: "Importado",
    doneBody: "Se agregaron {guests} invitados. Se registraron {rsvps} respuestas.",
    done: "Ver la lista",
    startOver: "Empezar de nuevo",
    error: "No se pudo leer.",
    noPhone: "sin teléfono",
  },
};
