/* Failure-safe texture loading.
   Textures under /textures/*.jpg are generated by another workstream and may
   not exist yet; a 404 must never crash or suspend the canvas. Loads via
   THREE.TextureLoader and simply stays null on error so components can render
   a flat brand-color fallback material instead. */

import { useEffect, useState } from 'react';
import * as THREE from 'three';

export function useSafeTexture(url: string): THREE.Texture | null {
  const [texture, setTexture] = useState<THREE.Texture | null>(null);

  useEffect(() => {
    let cancelled = false;
    let loaded: THREE.Texture | null = null;

    new THREE.TextureLoader().load(
      url,
      (tex) => {
        if (cancelled) {
          tex.dispose();
          return;
        }
        tex.colorSpace = THREE.SRGBColorSpace;
        tex.anisotropy = 4;
        loaded = tex;
        setTexture(tex);
      },
      undefined,
      () => {
        /* Missing or failed texture: leave null, components fall back. */
        if (!cancelled) setTexture(null);
      },
    );

    return () => {
      cancelled = true;
      loaded?.dispose();
      setTexture(null);
    };
  }, [url]);

  return texture;
}
