// Couple settings that used to live only on the web: reminders, email
// notifications, the invite code.

export const COPY = {
  en: {
    notifications: {
      title: "Email notifications",
      subtitle: "What Guest-ly emails you.",
      rsvpEmail: "New RSVP emails",
      rsvpEmailHint: "One email each time a guest answers.",
      weeklyDigest: "Monday digest",
      weeklyDigestHint: "A short summary every Monday: answers, questions, tasks due.",
      pushNote: "Push notifications are set from the app settings.",
    },
    reminders: {
      title: "Automatic reminders",
      subtitle: "Nudge guests who have not answered, on WhatsApp.",
      enabled: "Send reminders automatically",
      enabledHint: "Only to guests with a phone on file who have not answered yet.",
      offsets: "Days before the wedding",
      offsetsHint: "Tap to add or remove a day.",
      addDay: "Add a day",
      dayPlaceholder: "Days",
      window: "Send window",
      windowHint: "Local time in {tz}. Reminders only go out between these hours.",
      from: "From",
      to: "Until",
      minGap: "Minimum days between reminders to the same guest",
      lastRun: "Last run: {day}",
      neverRun: "No reminder sent yet.",
      save: "Save",
      saved: "Saved",
      pending: "The reminder settings are being set up for this wedding. Try again in a moment.",
      readOnly: "Only the couple can change these settings.",
    },
    invite: {
      title: "Invitation code",
      subtitle: "Guests type this in the app to open your wedding.",
      code: "Code",
      link: "Link",
      copy: "Copy",
      copied: "Copied",
      share: "Share",
      shareText: "Open our wedding in the Guest-ly app with the code {code}: {url}",
      regenerate: "Make a new code",
      regenerateConfirm: "The current code stops working right away. Anyone who already opened the wedding stays signed in. Continue?",
      pending: "The invitation code is being set up. Try again in a moment.",
    },
  },
  es: {
    notifications: {
      title: "Notificaciones por correo",
      subtitle: "Lo que Guest-ly le envía por correo.",
      rsvpEmail: "Correos de nuevas confirmaciones",
      rsvpEmailHint: "Un correo cada vez que un invitado responde.",
      weeklyDigest: "Resumen de los lunes",
      weeklyDigestHint: "Un resumen breve cada lunes: respuestas, preguntas, tareas por vencer.",
      pushNote: "Las notificaciones push se configuran en los ajustes de la app.",
    },
    reminders: {
      title: "Recordatorios automáticos",
      subtitle: "Recuerde por WhatsApp a quienes aún no respondieron.",
      enabled: "Enviar recordatorios automáticamente",
      enabledHint: "Solo a invitados con teléfono registrado que aún no han respondido.",
      offsets: "Días antes de la boda",
      offsetsHint: "Toque para agregar o quitar un día.",
      addDay: "Agregar un día",
      dayPlaceholder: "Días",
      window: "Horario de envío",
      windowHint: "Hora local de {tz}. Los recordatorios solo salen entre estas horas.",
      from: "Desde",
      to: "Hasta",
      minGap: "Días mínimos entre recordatorios al mismo invitado",
      lastRun: "Último envío: {day}",
      neverRun: "Aún no se envió ningún recordatorio.",
      save: "Guardar",
      saved: "Guardado",
      pending: "Los recordatorios se están preparando para esta boda. Inténtelo de nuevo en un momento.",
      readOnly: "Solo la pareja puede cambiar estos ajustes.",
    },
    invite: {
      title: "Código de invitación",
      subtitle: "Los invitados lo escriben en la app para abrir su boda.",
      code: "Código",
      link: "Enlace",
      copy: "Copiar",
      copied: "Copiado",
      share: "Compartir",
      shareText: "Abra nuestra boda en la app Guest-ly con el código {code}: {url}",
      regenerate: "Generar un código nuevo",
      regenerateConfirm: "El código actual deja de funcionar de inmediato. Quienes ya abrieron la boda siguen dentro. ¿Continuar?",
      pending: "El código de invitación se está preparando. Inténtelo de nuevo en un momento.",
    },
  },
};
