export const COPY = {
  en: {
    title: "Coordinator",
    subtitleCouple: "Reads your wedding, proposes changes, does nothing until you confirm.",
    subtitlePlanner: "Reads this wedding and files requests to the couple for you.",
    newChat: "New chat",
    chats: "Your chats",
    noChats: "No chats yet.",
    untitled: "Untitled chat",
    delete: "Delete",
    deleteConfirm: "Delete this chat and its history?",
    cancel: "Cancel",
    emptyTitle: "Ask anything about your wedding.",
    emptyBody: "Who has not answered, what the shuttle plan says, add a guest, update a travel tip, send a reminder. The Coordinator reads first and proposes; nothing changes until you tap Confirm.",
    emptyBodyPlanner: "Ask about the guest list, the RSVP status or the board. Changes go to the couple as requests; nothing changes until they approve.",
    placeholder: "Ask the Coordinator",
    send: "Send",
    working: "Working",
    confirm: "Confirm",
    cancelCard: "Cancel",
    typedHint: "Type SEND to confirm this broadcast.",
    typedPlaceholder: "SEND",
    recipients: "{n} recipients",
    statusExecuted: "Done",
    statusCancelled: "Cancelled",
    statusFailed: "Failed",
    statusExpired: "Expired",
    statusProposed: "Waiting for your confirmation",
    before: "Before",
    notEnabledTitle: "Not switched on",
    chips: ["Who has not RSVPd yet?", "How many guests confirmed?", "Add a guest", "Send a reminder to non responders"],
    chipsPlanner: ["How many guests confirmed?", "Who is still pending?", "What is on the board?"],
    error: "The Coordinator could not finish that. Please try again.",
    offline: "You are offline. The Coordinator needs a connection.",
    readOnly: "Your role can read the chat but not send.",
    tools: {
      get_guests: "Reading the guest list",
      get_non_responders: "Finding non responders",
      get_rsvp: "Reading RSVP",
      get_brain_facts: "Reading the Wedding Brain",
      get_brain_versions: "Reading Brain versions",
      get_broadcast_history: "Reading broadcast history",
      get_reminder_config: "Reading reminder settings",
      get_analytics_summary: "Reading analytics",
      add_guest: "Preparing guest",
      update_guest: "Preparing update",
      remove_guest: "Preparing removal",
      upsert_rsvp: "Preparing RSVP",
      import_guests: "Preparing the import",
      bulk_update_rsvps: "Preparing RSVP updates",
      propose_brain_edit: "Preparing Brain edit",
      publish_brain_draft: "Preparing publish",
      send_broadcast: "Preparing broadcast",
      resolve_escalation: "Resolving the question",
      list_open_escalations: "Reading open questions",
      get_seating_summary: "Reading the seating plan",
      export_guest_list: "Preparing the export",
      get_answer_policy: "Reading the answer policy",
      set_answer_policy: "Preparing the answer policy",
      get_website_config: "Reading the website",
      update_website_section: "Preparing the website edit",
      set_registry: "Preparing the registry",
      set_website_published: "Preparing the website",
      list_vendors: "Reading the vendors",
      get_runsheet: "Reading the runsheet",
      get_budget_summary: "Reading the budget",
      get_board: "Reading the board",
      file_request: "Preparing the request",
      add_board_task: "Preparing the task",
      update_board_task: "Preparing the task update",
      web_search: "Searching the web",
    } as Record<string, string>,
    bubbleCoordinator: "Ask the Coordinator",
    bubbleConcierge: "Ask the concierge",
  },
  es: {
    title: "Coordinador",
    subtitleCouple: "Lee su boda, propone cambios y no hace nada hasta que usted confirme.",
    subtitlePlanner: "Lee esta boda y presenta solicitudes a los novios por usted.",
    newChat: "Nuevo chat",
    chats: "Sus chats",
    noChats: "Todavía no hay chats.",
    untitled: "Chat sin título",
    delete: "Eliminar",
    deleteConfirm: "¿Eliminar este chat y su historial?",
    cancel: "Cancelar",
    emptyTitle: "Pregunte lo que quiera sobre su boda.",
    emptyBody: "Quién no ha respondido, qué dice el plan del transporte, agregar un invitado, actualizar un consejo de viaje, enviar un recordatorio. El Coordinador primero lee y propone; nada cambia hasta que usted toque Confirmar.",
    emptyBodyPlanner: "Pregunte por la lista de invitados, el estado de los RSVP o el tablero. Los cambios llegan a los novios como solicitudes; nada cambia hasta que ellos aprueben.",
    placeholder: "Pregunte al Coordinador",
    send: "Enviar",
    working: "Trabajando",
    confirm: "Confirmar",
    cancelCard: "Cancelar",
    typedHint: "Escriba ENVIAR para confirmar esta difusión.",
    typedPlaceholder: "ENVIAR",
    recipients: "{n} destinatarios",
    statusExecuted: "Hecho",
    statusCancelled: "Cancelado",
    statusFailed: "Falló",
    statusExpired: "Expiró",
    statusProposed: "Esperando su confirmación",
    before: "Antes",
    notEnabledTitle: "No está activado",
    chips: ["¿Quién no ha respondido todavía?", "¿Cuántos invitados confirmaron?", "Agrega un invitado", "Envía un recordatorio a los pendientes"],
    chipsPlanner: ["¿Cuántos invitados confirmaron?", "¿Quién sigue pendiente?", "¿Qué hay en el tablero?"],
    error: "El Coordinador no pudo terminar eso. Inténtelo de nuevo.",
    offline: "Está sin conexión. El Coordinador necesita conexión.",
    readOnly: "Su rol puede leer el chat pero no enviar.",
    tools: {
      get_guests: "Leyendo la lista de invitados",
      get_non_responders: "Buscando pendientes",
      get_rsvp: "Leyendo RSVP",
      get_brain_facts: "Leyendo el Wedding Brain",
      get_brain_versions: "Leyendo versiones del Brain",
      get_broadcast_history: "Leyendo historial de difusiones",
      get_reminder_config: "Leyendo recordatorios",
      get_analytics_summary: "Leyendo analíticas",
      add_guest: "Preparando invitado",
      update_guest: "Preparando cambio",
      remove_guest: "Preparando eliminación",
      upsert_rsvp: "Preparando RSVP",
      import_guests: "Preparando la importación",
      bulk_update_rsvps: "Preparando cambios de RSVP",
      propose_brain_edit: "Preparando edición del Brain",
      publish_brain_draft: "Preparando publicación",
      send_broadcast: "Preparando difusión",
      resolve_escalation: "Resolviendo la pregunta",
      list_open_escalations: "Leyendo preguntas abiertas",
      get_seating_summary: "Leyendo el plano de mesas",
      export_guest_list: "Preparando la exportación",
      get_answer_policy: "Leyendo la política de respuestas",
      set_answer_policy: "Preparando la política de respuestas",
      get_website_config: "Leyendo el sitio web",
      update_website_section: "Preparando el cambio del sitio",
      set_registry: "Preparando la mesa de regalos",
      set_website_published: "Preparando el sitio",
      list_vendors: "Leyendo los proveedores",
      get_runsheet: "Leyendo el runsheet",
      get_budget_summary: "Leyendo el presupuesto",
      get_board: "Leyendo el tablero",
      file_request: "Preparando la solicitud",
      add_board_task: "Preparando la tarea",
      update_board_task: "Preparando el cambio de tarea",
      web_search: "Buscando en la web",
    } as Record<string, string>,
    bubbleCoordinator: "Pregunte al Coordinador",
    bubbleConcierge: "Pregunte al concierge",
  },
};
