// Copy for the build 12 guest screens (tabs Invitation, Schedule, Ask, Info;
// the one-screen RSVP, the confirmation, the Home sheets). A feature module so
// the guest work never edits the shared en.ts / es.ts dictionaries. Spanish
// uses tú. No dashes in copy.

const en = {
  tabs: { invitation: "Invitation", schedule: "Schedule", ask: "Ask", info: "Info" },
  home: {
    invitedTo: "You're invited to the wedding of",
    willYouCome: "Will you be there?",
    replyBy: "Reply by {date}.",
    replyAnyTime: "The couple would love your reply.",
    replyNow: "Reply now",
    draftLine: "Your reply is almost ready. Finish it and send it.",
    finishReply: "Finish reply",
    repliedCount: "{n} guests have replied",
    yourReply: "Your reply",
    goingParty: "You're going, party of {n}",
    goingOne: "You're going",
    notGoing: "You can't make it",
    coupleKnows: "The couple already knows.",
    changeUntil: "You can change it until {date}.",
    changeAnyTime: "You can change it any time.",
    closed: "Replies are closed. If something changed, tell the couple.",
    change: "Change",
    shortcuts: "Shortcuts",
    directions: "Directions",
    dressCode: "Dress code",
    hotels: "Hotels",
    gifts: "Gifts",
    days: "days",
    day: "day",
    until: "until {date}",
    dayStatusPending: "Reply pending",
  },
  directions: {
    title: "Directions",
    openMaps: "Open in Maps",
    copyAddress: "Copy address",
    copied: "Address copied",
    arrival: "Arrival advice",
    none: "The couple has not added the venue yet. Ask the concierge.",
  },
  sheet: {
    askConcierge: "Ask the concierge",
    seeAll: "See it all",
  },
  rsvp: {
    title: "Your reply",
    introPending: "Reply by {date}. You can change it later.",
    introPendingNoDate: "You can change it later.",
    introChange: "Change what you need and send it again. {couple} will see the new one.",
    allGoingParty: "Everyone's coming to everything",
    allGoingOne: "I'm coming to everything",
    noneGoingParty: "We can't make it",
    noneGoingOne: "I can't make it",
    goingYou: "Going",
    goingOther: "Going",
    notGoingYou: "Can't go",
    notGoingOther: "Can't go",
    you: "You",
    missing: "Missing",
    missingYou: "Your reply is missing",
    missingOther: "{name}'s reply is missing",
    questionsMissing: "Answer the questions marked required",
    addNote: "Add a note",
    noteLabel: "Note for {couple}",
    optional: "Optional",
    notePlaceholder: "Allergies, a song they have to play, or just hello",
    send: "Send reply",
    sending: "Sending...",
    pickFirst: "Answer every event for each person to send.",
  },
  confirm: {
    onTheList: "You're on the list, {name}.",
    thanks: "Thanks for letting them know, {name}.",
    haveReply: "{couple} have your reply.",
    willMiss: "{couple} know. They will miss you.",
    yourReply: "Your reply",
    youGoingTo: "Going to {events}",
    otherGoingTo: "Going to {events}",
    youEverything: "Going to everything",
    otherEverything: "Going to everything",
    youCantGo: "Can't go",
    otherCantGo: "Can't go",
    note: "Your note",
    addCalendar: "Add to calendar",
    changeReply: "Change reply",
    notifAsk: "Want a reminder the day before and updates on the wedding day?",
    notifYes: "Yes, remind me",
    notifNo: "Not now",
    notifOn: "Notifications are on. We will remind you the day before.",
    notifLater: "No notifications for now. You can turn them on in Info.",
    and: "and",
  },
  ask: {
    title: "Ask",
    aiNotice: "Answered by an AI that knows the wedding",
    aiLabel: "Artificial intelligence",
    aiTitle: "An AI that knows this wedding answers",
    aiBody1: "It knows what {couple} taught it: the schedule, the venues, the hotels, the gifts and the dress code.",
    aiBody2: "If it does not know something, it does not make it up: it asks them, and their answer shows up in this thread with a gold border.",
    hello: "Hi {name}. I know the schedule, the venues, the hotels, the gifts and the dress code. Anything I do not know, I ask {couple}.",
    fromCouple: "From {couple}",
    concierge: "Concierge",
    placeholder: "Type your question",
    passed: "Question sent to {couple}. Their answer shows up right here.",
    waiting: "Waiting for {couple}",
    newLabel: "New",
    earlier: "See earlier messages",
    chips: { wear: "What should I wear?", stay: "Where should I stay?", time: "What time does it start?", gifts: "Is there a gift registry?" },
  },
  schedule: {
    title: "Schedule",
    addAll: "Add it all to your calendar",
    addOne: "Add to calendar",
    calendarNote: "Each event comes with a reminder the day before.",
    notGoing: "You are not going to this one",
    dressCode: "Dress code",
    arrival: "Arrival advice",
    directions: "Directions",
    empty: "The couple has not shared the schedule yet.",
  },
  info: {
    title: "Info",
    wedding: "The wedding",
    story: "Our story",
    photos: "Photos",
    faq: "Questions",
    hotels: "Hotels",
    gifts: "Gifts",
    dressCode: "Dress code",
    site: "Wedding site",
    settings: "Settings",
    language: "Language",
    notifications: "Notifications",
    on: "On",
    off: "Off",
    leave: "Leave this wedding",
    leaveTitle: "Leave {couple}'s wedding?",
    leaveBody: "Your reply stays saved. To come back you need your invitation code.",
    leaveCode: "Your code: {code}",
    leaveGo: "Leave",
  },
  find: {
    codeOk: "Code accepted",
    hint: "3 letters are enough.",
    privacy: "We only show names that match, never the whole list.",
    intro: "Type it as it appears on your invitation.",
  },
  invite: {
    continue: "Continue",
  },
};

const es: typeof en = {
  tabs: { invitation: "Invitación", schedule: "Programa", ask: "Preguntar", info: "Info" },
  home: {
    invitedTo: "Te invitan a la boda de",
    willYouCome: "¿Vienes?",
    replyBy: "Responde antes del {date}.",
    replyAnyTime: "A la pareja le encantaría tu respuesta.",
    replyNow: "Responder ahora",
    draftLine: "Tu respuesta está casi lista. Termínala y envíala.",
    finishReply: "Terminar respuesta",
    repliedCount: "{n} invitados ya respondieron",
    yourReply: "Tu respuesta",
    goingParty: "Vas con {n}",
    goingOne: "Vas",
    notGoing: "No vas",
    coupleKnows: "La pareja ya lo sabe.",
    changeUntil: "Puedes cambiarla hasta el {date}.",
    changeAnyTime: "Puedes cambiarla cuando quieras.",
    closed: "Las respuestas ya cerraron. Si algo cambió, avísale a la pareja.",
    change: "Cambiar",
    shortcuts: "Accesos",
    directions: "Cómo llegar",
    dressCode: "Código de vestimenta",
    hotels: "Hoteles",
    gifts: "Regalos",
    days: "días",
    day: "día",
    until: "para el {date}",
    dayStatusPending: "Falta tu respuesta",
  },
  directions: {
    title: "Cómo llegar",
    openMaps: "Abrir en Mapas",
    copyAddress: "Copiar dirección",
    copied: "Dirección copiada",
    arrival: "Consejo de llegada",
    none: "La pareja todavía no agregó el lugar. Pregúntale al concierge.",
  },
  sheet: {
    askConcierge: "Pregúntale al concierge",
    seeAll: "Ver todo",
  },
  rsvp: {
    title: "Tu respuesta",
    introPending: "Responde antes del {date}. Puedes cambiarla después.",
    introPendingNoDate: "Puedes cambiarla después.",
    introChange: "Cambia lo que necesites y vuelve a enviarla. {couple} verán la nueva.",
    allGoingParty: "Vamos todos a todo",
    allGoingOne: "Voy a todo",
    noneGoingParty: "No podemos ir",
    noneGoingOne: "No puedo ir",
    goingYou: "Voy",
    goingOther: "Va",
    notGoingYou: "No voy",
    notGoingOther: "No va",
    you: "Tú",
    missing: "Falta",
    missingYou: "Falta tu respuesta",
    missingOther: "Falta la respuesta de {name}",
    questionsMissing: "Responde las preguntas obligatorias",
    addNote: "Agrega una nota",
    noteLabel: "Nota para {couple}",
    optional: "Opcional",
    notePlaceholder: "Alergias, una canción que no puede faltar o solo un saludo",
    send: "Enviar respuesta",
    sending: "Enviando...",
    pickFirst: "Responde cada evento por cada persona para enviar.",
  },
  confirm: {
    onTheList: "Estás en la lista, {name}.",
    thanks: "Gracias por avisar, {name}.",
    haveReply: "{couple} ya tienen tu respuesta.",
    willMiss: "{couple} ya lo saben. Te van a extrañar.",
    yourReply: "Tu respuesta",
    youGoingTo: "Vas a {events}",
    otherGoingTo: "Va a {events}",
    youEverything: "Vas a todo",
    otherEverything: "Va a todo",
    youCantGo: "No vas",
    otherCantGo: "No va",
    note: "Tu nota",
    addCalendar: "Agregar al calendario",
    changeReply: "Cambiar respuesta",
    notifAsk: "¿Quieres un aviso un día antes y novedades el día de la boda?",
    notifYes: "Sí, avísame",
    notifNo: "Ahora no",
    notifOn: "Avisos activados. Te recordamos un día antes.",
    notifLater: "Sin avisos por ahora. Puedes activarlos en Info.",
    and: "y",
  },
  ask: {
    title: "Preguntar",
    aiNotice: "Responde una IA que conoce la boda",
    aiLabel: "Inteligencia artificial",
    aiTitle: "Contesta una IA que conoce esta boda",
    aiBody1: "Sabe lo que {couple} le enseñaron: el programa, los lugares, los hoteles, los regalos y la vestimenta.",
    aiBody2: "Si no sabe algo, no lo inventa: se lo pregunta a ellos y su respuesta te llega en este mismo hilo, con borde dorado.",
    hello: "Hola, {name}. Conozco el programa, los lugares, los hoteles, los regalos y el código de vestimenta. Lo que no sepa, se lo pregunto a {couple}.",
    fromCouple: "De {couple}",
    concierge: "Concierge",
    placeholder: "Escribe tu pregunta",
    passed: "Pregunta enviada a {couple}. Su respuesta te llega aquí mismo.",
    waiting: "Esperando a {couple}",
    newLabel: "Nuevo",
    earlier: "Ver mensajes anteriores",
    chips: { wear: "¿Qué me pongo?", stay: "¿Dónde me hospedo?", time: "¿A qué hora empieza?", gifts: "¿Hay mesa de regalos?" },
  },
  schedule: {
    title: "Programa",
    addAll: "Agregar todo al calendario",
    addOne: "Agregar al calendario",
    calendarNote: "Cada evento lleva un aviso un día antes.",
    notGoing: "No vas a este evento",
    dressCode: "Código de vestimenta",
    arrival: "Consejo de llegada",
    directions: "Cómo llegar",
    empty: "La pareja todavía no compartió el programa.",
  },
  info: {
    title: "Info",
    wedding: "La boda",
    story: "Nuestra historia",
    photos: "Fotos",
    faq: "Preguntas frecuentes",
    hotels: "Hoteles",
    gifts: "Regalos",
    dressCode: "Código de vestimenta",
    site: "Sitio de la boda",
    settings: "Ajustes",
    language: "Idioma",
    notifications: "Notificaciones",
    on: "Activadas",
    off: "Desactivadas",
    leave: "Salir de esta boda",
    leaveTitle: "¿Salir de la boda de {couple}?",
    leaveBody: "Tu respuesta se queda guardada. Para volver necesitas tu código de invitación.",
    leaveCode: "Tu código: {code}",
    leaveGo: "Salir",
  },
  find: {
    codeOk: "Código correcto",
    hint: "Con 3 letras basta.",
    privacy: "Solo mostramos los nombres que coinciden, nunca la lista completa.",
    intro: "Escríbelo como aparece en tu invitación.",
  },
  invite: {
    continue: "Continuar",
  },
};

export const GUEST_COPY = { en, es };
export type GuestCopy = typeof en;
