// Tasks copy, both languages. Keys mirror the web tasks page so wording
// stays the same across surfaces.

const en = {
  title: "Tasks",
  subtitle: "Everything that has to happen before the day.",
  progress: "{done} of {total} done",
  segments: { ours: "Our list", board: "With the planner" },
  groups: {
    overdue: "Overdue",
    today: "Today",
    week: "This week",
    later: "Later",
    undated: "No date",
    done: "Done",
  },
  categories: {
    legal: "Legal",
    venue: "Venue",
    vendors: "Vendors",
    guests: "Guests",
    budget: "Budget",
    travel: "Travel",
    attire: "Attire",
    ceremony: "Ceremony",
    day_of: "Day of",
    other: "Other",
  },
  statuses: { todo: "To do", doing: "In progress", blocked: "Blocked", done: "Done" },
  priorities: { low: "Low", normal: "Normal", high: "High" },
  recurrences: { none: "Does not repeat", weekly: "Every week", monthly: "Every month" },
  boardStatuses: { open: "Open", in_progress: "In progress", done: "Done" },
  assignedTo: { couple: "Couple", planner: "Planner" },
  filters: { all: "All", open: "Open", done: "Done" },
  add: "Add a task",
  addBoard: "Add to the board",
  newTask: "New task",
  newBoardTask: "New shared task",
  editTask: "Edit task",
  fields: {
    title: "Title",
    notes: "Notes",
    detail: "Details",
    category: "Category",
    status: "Status",
    priority: "Priority",
    dueDate: "Due date",
    dueHint: "YYYY-MM-DD",
    recurrence: "Repeats",
    owner: "Owner",
    noOwner: "No one yet",
    reminders: "Remind me",
    remindersHint: "Days before the due date. Reminder email goes out when reminders are on.",
    assignedTo: "Assigned to",
    guests: "Guests involved",
  },
  dateChips: { none: "No date", today: "Today", week: "In a week", month: "In a month" },
  save: "Save",
  create: "Create task",
  cancel: "Cancel",
  delete: "Delete task",
  deleteConfirmTitle: "Delete this task?",
  deleteConfirmBody: "It disappears from the list for everyone. This cannot be undone.",
  markDone: "Mark done",
  reopen: "Reopen",
  dueIn: "Due in {n} days",
  dueTomorrow: "Due tomorrow",
  dueToday: "Due today",
  overdueBy: "{n} days overdue",
  overdueOne: "1 day overdue",
  completedAt: "Completed {when}",
  repeatCloned: "Done. The next one is set for {date}.",
  emptyTitle: "No tasks yet",
  emptyBody: "Start from the wedding checklist or add your own.",
  emptyBoardTitle: "Nothing on the board",
  emptyBoardBody: "Tasks you share with your planner show up here.",
  emptyDone: "Nothing finished yet",
  checklist: "Wedding checklist",
  checklistIntro: "Tried and tested tasks, dated from your wedding day. Pick the ones you want; applied ones never duplicate.",
  checklistApply: "Add {n} tasks",
  checklistApplied: "Already on your list",
  checklistPast: "Due date already passed, lands today",
  checklistAddedToast: "{n} tasks added",
  selectAll: "Select all",
  clearAll: "Clear",
  collaborators: "People",
  collaboratorsIntro: "Portal members can own tasks. Add helpers without a login here; they get reminder email in their language.",
  members: "Portal members",
  helpers: "Helpers",
  addHelper: "Add a helper",
  editHelper: "Edit helper",
  helperFields: { name: "Name", role: "Role (optional)", email: "Email", phone: "Phone (optional)", language: "Language", notify: "Send reminder email" },
  removeHelper: "Remove helper",
  removeHelperBody: "Tasks they own become unassigned.",
  reminders: "Reminders and calendar",
  remindersSwitch: "Email reminders",
  remindersBody: "One email per day in the morning, in your timezone, when a task is due soon or overdue.",
  feedTitle: "Calendar feed",
  feedBody: "Subscribe from Apple Calendar or Google Calendar. Anyone with the link sees your tasks, so keep it private.",
  copyLink: "Copy link",
  copied: "Link copied",
  rotate: "Make a new link",
  rotateBody: "The old link stops working for everyone who has it.",
  comments: "Comments",
  addComment: "Write a comment",
  send: "Send",
  noComments: "No comments yet.",
  createdBy: "Added by {who}",
  pending: "Almost ready. This part of the portal is still being set up.",
  offline: "You are offline. Changes need a connection.",
  errorTitle: "Give it a title",
  error: "That did not save. Please try again.",
  moreOptions: "More options",
  lessOptions: "Fewer options",
  planner: {
    title: "Tasks",
    subtitle: "The board you share with the couple.",
    mine: "Mine",
    theirs: "Couple",
  },
};

const es: typeof en = {
  title: "Tareas",
  subtitle: "Todo lo que tiene que pasar antes del gran día.",
  progress: "{done} de {total} listas",
  segments: { ours: "Nuestra lista", board: "Con el planner" },
  groups: {
    overdue: "Atrasadas",
    today: "Hoy",
    week: "Esta semana",
    later: "Más adelante",
    undated: "Sin fecha",
    done: "Completas",
  },
  categories: {
    legal: "Legal",
    venue: "Lugar",
    vendors: "Proveedores",
    guests: "Invitados",
    budget: "Presupuesto",
    travel: "Viaje",
    attire: "Vestimenta",
    ceremony: "Ceremonia",
    day_of: "Día de la boda",
    other: "Otros",
  },
  statuses: { todo: "Por hacer", doing: "En curso", blocked: "Bloqueada", done: "Completa" },
  priorities: { low: "Baja", normal: "Normal", high: "Alta" },
  recurrences: { none: "No se repite", weekly: "Cada semana", monthly: "Cada mes" },
  boardStatuses: { open: "Abierta", in_progress: "En curso", done: "Completa" },
  assignedTo: { couple: "Pareja", planner: "Planner" },
  filters: { all: "Todas", open: "Abiertas", done: "Completas" },
  add: "Agregar una tarea",
  addBoard: "Agregar al tablero",
  newTask: "Nueva tarea",
  newBoardTask: "Nueva tarea compartida",
  editTask: "Editar tarea",
  fields: {
    title: "Título",
    notes: "Notas",
    detail: "Detalles",
    category: "Categoría",
    status: "Estado",
    priority: "Prioridad",
    dueDate: "Fecha límite",
    dueHint: "AAAA-MM-DD",
    recurrence: "Se repite",
    owner: "Responsable",
    noOwner: "Nadie todavía",
    reminders: "Recordarme",
    remindersHint: "Días antes de la fecha límite. El correo sale cuando los recordatorios están activados.",
    assignedTo: "Asignada a",
    guests: "Invitados relacionados",
  },
  dateChips: { none: "Sin fecha", today: "Hoy", week: "En una semana", month: "En un mes" },
  save: "Guardar",
  create: "Crear tarea",
  cancel: "Cancelar",
  delete: "Eliminar tarea",
  deleteConfirmTitle: "¿Eliminar esta tarea?",
  deleteConfirmBody: "Desaparece de la lista para todos. No se puede deshacer.",
  markDone: "Marcar completa",
  reopen: "Reabrir",
  dueIn: "Vence en {n} días",
  dueTomorrow: "Vence mañana",
  dueToday: "Vence hoy",
  overdueBy: "{n} días de atraso",
  overdueOne: "1 día de atraso",
  completedAt: "Completada {when}",
  repeatCloned: "Lista. La siguiente queda para el {date}.",
  emptyTitle: "Todavía no hay tareas",
  emptyBody: "Empiece por la lista de la boda o agregue las suyas.",
  emptyBoardTitle: "Nada en el tablero",
  emptyBoardBody: "Las tareas que comparte con su planner aparecen aquí.",
  emptyDone: "Nada terminado todavía",
  checklist: "Lista de la boda",
  checklistIntro: "Tareas probadas, con fecha calculada desde su boda. Elija las que quiera; las ya agregadas nunca se duplican.",
  checklistApply: "Agregar {n} tareas",
  checklistApplied: "Ya está en su lista",
  checklistPast: "La fecha ya pasó, queda para hoy",
  checklistAddedToast: "{n} tareas agregadas",
  selectAll: "Seleccionar todas",
  clearAll: "Limpiar",
  collaborators: "Personas",
  collaboratorsIntro: "Los miembros del portal pueden ser responsables. Agregue aquí ayudantes sin cuenta; reciben el correo de recordatorio en su idioma.",
  members: "Miembros del portal",
  helpers: "Ayudantes",
  addHelper: "Agregar ayudante",
  editHelper: "Editar ayudante",
  helperFields: { name: "Nombre", role: "Rol (opcional)", email: "Correo", phone: "Teléfono (opcional)", language: "Idioma", notify: "Enviar correo de recordatorio" },
  removeHelper: "Quitar ayudante",
  removeHelperBody: "Sus tareas quedan sin responsable.",
  reminders: "Recordatorios y calendario",
  remindersSwitch: "Recordatorios por correo",
  remindersBody: "Un correo al día por la mañana, en su zona horaria, cuando una tarea vence pronto o está atrasada.",
  feedTitle: "Calendario suscribible",
  feedBody: "Suscríbase desde Apple Calendar o Google Calendar. Cualquiera con el enlace ve sus tareas, así que manténgalo privado.",
  copyLink: "Copiar enlace",
  copied: "Enlace copiado",
  rotate: "Generar un enlace nuevo",
  rotateBody: "El enlace anterior deja de funcionar para todos los que lo tengan.",
  comments: "Comentarios",
  addComment: "Escriba un comentario",
  send: "Enviar",
  noComments: "Todavía no hay comentarios.",
  createdBy: "Agregada por {who}",
  pending: "Casi listo. Esta parte del portal todavía se está configurando.",
  offline: "Está sin conexión. Los cambios necesitan conexión.",
  errorTitle: "Póngale un título",
  error: "No se guardó. Inténtelo de nuevo.",
  moreOptions: "Más opciones",
  lessOptions: "Menos opciones",
  planner: {
    title: "Tareas",
    subtitle: "El tablero que comparte con la pareja.",
    mine: "Mías",
    theirs: "Pareja",
  },
};

export const COPY = { en, es };
export type TasksCopy = typeof en;
