export const COPY = {
  en: {
    title: "Concierge insights",
    subtitle: "What guests ask, what the concierge could not answer, and who waits on you.",
    window: (d: number) => `Last ${d} days`,
    messages: "guest messages",
    guests: "guests",
    deflection: "answered by the concierge",
    attention: "upset threads",
    gapsTitle: "Gaps to fix",
    gapsSub: "The concierge could not answer these. Add the answer and it learns for next time.",
    gapsEmpty: "No open gaps. Your concierge answered everything.",
    asked: (n: number) => (n === 1 ? "asked once" : `asked ${n} times`),
    answer: "Answer",
    dismiss: "Dismiss",
    answerPlaceholder: "Write the answer guests should get",
    publishAnswer: "Publish answer",
    answered: "Published. The concierge knows the answer now.",
    escalationsTitle: "Waiting on you",
    escalationsSub: "Questions the concierge handed to you.",
    escalationsEmpty: "Nobody is waiting on you.",
    openConversation: "Open conversation",
    resolve: "Mark handled",
    resolved: "Marked handled.",
    topTitle: "Top questions",
    topEmpty: "No questions yet. Share the invite code and the concierge starts learning.",
    trendNew: "new",
    trendUp: (n: number) => `+${n}`,
    trendDown: (n: number) => `${n}`,
    trendFlat: "same",
    activity: "Daily activity",
    web: "web",
    whatsapp: "WhatsApp",
    statsUnavailable: "Metrics are not available right now; the lists below still work.",
    readOnly: "Read only: owners and admins act on gaps.",
  },
  es: {
    title: "Métricas del concierge",
    subtitle: "Qué preguntan los invitados, qué no pudo responder el concierge y quién te espera.",
    window: (d: number) => `Últimos ${d} días`,
    messages: "mensajes de invitados",
    guests: "invitados",
    deflection: "respondido por el concierge",
    attention: "conversaciones tensas",
    gapsTitle: "Pendientes por resolver",
    gapsSub: "El concierge no pudo responder esto. Agrega la respuesta y la aprende para la próxima.",
    gapsEmpty: "No hay pendientes. Tu concierge respondió todo.",
    asked: (n: number) => (n === 1 ? "preguntado una vez" : `preguntado ${n} veces`),
    answer: "Responder",
    dismiss: "Descartar",
    answerPlaceholder: "Escribe la respuesta que deben recibir los invitados",
    publishAnswer: "Publicar respuesta",
    answered: "Publicado. El concierge ya conoce la respuesta.",
    escalationsTitle: "Esperando por ti",
    escalationsSub: "Preguntas que el concierge te pasó.",
    escalationsEmpty: "Nadie está esperando por ti.",
    openConversation: "Abrir conversación",
    resolve: "Marcar como atendida",
    resolved: "Marcada como atendida.",
    topTitle: "Preguntas frecuentes",
    topEmpty: "Todavía no hay preguntas. Comparte el código de invitación y el concierge empieza a aprender.",
    trendNew: "nuevo",
    trendUp: (n: number) => `+${n}`,
    trendDown: (n: number) => `${n}`,
    trendFlat: "igual",
    activity: "Actividad diaria",
    web: "web",
    whatsapp: "WhatsApp",
    statsUnavailable: "Las métricas no están disponibles ahora; las listas de abajo sí funcionan.",
    readOnly: "Solo lectura: los dueños y administradores actúan sobre los pendientes.",
  },
};
