export const COPY = {
  en: {
    title: "RSVP questions",
    subtitle: "Asked when a guest answers. General questions go to everyone; event questions only to those attending that event.",
    empty: "No questions yet.",
    emptyBody: "Meal choice, song requests, arrival day. Keep it short: guests answer on their phone.",
    add: "Add a question",
    edit: "Question",
    labelEn: "Question in English",
    labelEs: "Pregunta en español",
    kind: "Answer type",
    select: "Choose one",
    text: "Free text",
    options: "Options",
    optionEn: "Option in English",
    optionEs: "Opción en español",
    addOption: "Add an option",
    scope: "Who is asked",
    everyone: "Everyone",
    required: "Required",
    save: "Save",
    saving: "Saving",
    delete: "Delete question",
    moveUp: "Move up",
    moveDown: "Move down",
    saved: "Saved",
    needLabel: "Write the question in at least one language.",
    needOptions: "Add at least two options.",
    max: "Up to 20 questions.",
    general: "general",
    optionsCount: "{n} options",
    freeText: "free text",
  },
  es: {
    title: "Preguntas del RSVP",
    subtitle: "Se hacen cuando un invitado responde. Las generales van a todos; las de evento solo a quienes asisten a ese evento.",
    empty: "Todavía no hay preguntas.",
    emptyBody: "Elección de menú, canciones, día de llegada. Sea breve: los invitados responden desde el teléfono.",
    add: "Agregar una pregunta",
    edit: "Pregunta",
    labelEn: "Question in English",
    labelEs: "Pregunta en español",
    kind: "Tipo de respuesta",
    select: "Elegir una",
    text: "Texto libre",
    options: "Opciones",
    optionEn: "Option in English",
    optionEs: "Opción en español",
    addOption: "Agregar una opción",
    scope: "A quién se pregunta",
    everyone: "A todos",
    required: "Obligatoria",
    save: "Guardar",
    saving: "Guardando",
    delete: "Eliminar pregunta",
    moveUp: "Subir",
    moveDown: "Bajar",
    saved: "Guardado",
    needLabel: "Escriba la pregunta en al menos un idioma.",
    needOptions: "Agregue al menos dos opciones.",
    max: "Hasta 20 preguntas.",
    general: "general",
    optionsCount: "{n} opciones",
    freeText: "texto libre",
  },
};
