// Wedding Brain copy. ES uses usted.
export const COPY = {
  en: {
    title: "Wedding brain",
    subtitle: "Everything your concierge knows. Edit, preview, publish.",
    live: (v: number) => `Version ${v} is live`,
    nothingLive: "Nothing published yet. Guests get no answers until you publish.",
    publishedAgo: (rel: string) => `Published ${rel}`,
    draftNotLive: "Your edits are not live yet. Publish to update your concierge.",
    inSync: "Everything here matches your live concierge.",
    saving: "Saving draft",
    saved: "Draft saved. Private until you publish.",
    saveFailed: "Could not save the draft.",
    publish: "Publish to the live concierge",
    publishing: "Publishing",
    published: (v: number) => `Published as v${v}. Your concierge picks it up within a minute.`,
    publishFailed: "Publish failed. Nothing changed for your guests.",
    sections: "Sections",
    complete: "Complete",
    empty: "Empty",
    items: (n: number) => (n === 1 ? "1 item" : `${n} items`),
    versions: "Version history",
    preview: "Ask the concierge",
    previewSub: "Test the live bot, or preview your unpublished edits.",
    readOnly: "You can read the brain but only owners and admins can edit it.",
    section: {
      couple: "Couple and date",
      itinerary: "Itinerary",
      travel: "Travel",
      hotels: "Hotels",
      transport: "Transportation",
      planner: "Planner",
      money: "Money",
      weather: "Weather and packing",
      local: "Local tips",
      food: "Food and things to do",
      gifts: "Gifts",
      faq: "Custom questions and answers",
    } as Record<string, string>,
    fields: {
      names: "Couple names",
      wedding_date: "Wedding date (YYYY-MM-DD)",
      location: "Location",
      website: "Wedding website",
      rsvp_link: "RSVP link",
      name: "Name",
      date: "Date (YYYY-MM-DD)",
      time: "Time",
      dress_code: "Dress code",
      maps_url: "Google Maps link",
      ceremony_location: "Ceremony location",
      ceremony_maps_url: "Ceremony maps link",
      reception_location: "Reception location",
      reception_maps_url: "Reception maps link",
      cost: "Cost",
      description: "Description",
      notes: "Notes",
      international: "International flights",
      domestic: "Domestic flights",
      visas: "Visas",
      arrival_advice: "Arrival advice",
      hotel: "Hotel",
      recommended: "Recommended",
      hotel_areas: "Best areas to stay",
      uber: "Ride apps",
      taxis: "Taxis",
      service_name: "Recommended service",
      whatsapp: "WhatsApp",
      link: "Link",
      planner_name: "Planner name",
      helps_with: "What they help with",
      plannerHint: "When the concierge cannot answer something, it sends guests here, and the question lands in your gaps list.",
      currency: "Currency and cards",
      exchange_rate: "Exchange rate guidance",
      exchanging: "Where to exchange",
      tipping: "Tipping",
      weather: "Weather",
      packing: "What to pack",
      grooming: "Grooming and appliances",
      altitude: "Altitude",
      electricity: "Electricity and plugs",
      communication: "Communication and SIM cards",
      health_safety: "Health and safety",
      restaurants: "Restaurants",
      food_to_try: "Food to try",
      things_region: "Things to do in the region",
      things_local: "Things to see locally",
      gifts: "Gifts and registry",
      question: "Question",
      answer: "Answer",
    } as Record<string, string>,
    event: (n: number) => `Event ${n}`,
    addEvent: "Add event",
    addHotel: "Add hotel",
    addQa: "Add question",
    addItem: "Add item",
    remove: "Remove",
    removeConfirm: "Remove this entry?",
    oneEntryPerLine: "One per line",
    listHint: "Each line becomes one entry.",
    gapBanner: "A guest asked this and your concierge could not answer. Add the answer and publish.",
    versionsTitle: "Version history",
    liveBadge: "Live",
    draftBadge: "Draft",
    restore: "Restore",
    restoreConfirm: (v: number) => `Publish version ${v} again? Guests get it within a minute.`,
    restored: (v: number) => `Version ${v} is live again.`,
    noVersions: "No versions yet.",
    askTitle: "Ask the concierge",
    modeLive: "Live bot",
    modeDraft: "My edits",
    liveHint: "This asks the real concierge your guests use. Give it a minute after publishing.",
    draftHint: "This answers from the edits on your phone, before anything goes live.",
    askPlaceholder: "Ask as a guest would",
    ask: "Ask",
    asking: "Asking",
    reply: "Reply",
    cancel: "Cancel",
    yes: "Yes",
  },
  es: {
    title: "Cerebro de la boda",
    subtitle: "Todo lo que sabe su concierge. Edite, pruebe, publique.",
    live: (v: number) => `La versión ${v} está en vivo`,
    nothingLive: "Todavía no hay nada publicado. Los invitados no reciben respuestas hasta que publique.",
    publishedAgo: (rel: string) => `Publicado ${rel}`,
    draftNotLive: "Sus cambios aún no están en vivo. Publique para actualizar su concierge.",
    inSync: "Todo aquí coincide con su concierge en vivo.",
    saving: "Guardando borrador",
    saved: "Borrador guardado. Es privado hasta que publique.",
    saveFailed: "No se pudo guardar el borrador.",
    publish: "Publicar al concierge en vivo",
    publishing: "Publicando",
    published: (v: number) => `Publicado como v${v}. Su concierge lo toma en menos de un minuto.`,
    publishFailed: "La publicación falló. Nada cambió para sus invitados.",
    sections: "Secciones",
    complete: "Completa",
    empty: "Vacía",
    items: (n: number) => (n === 1 ? "1 elemento" : `${n} elementos`),
    versions: "Historial de versiones",
    preview: "Pregunte al concierge",
    previewSub: "Pruebe el bot en vivo o sus cambios sin publicar.",
    readOnly: "Puede leer el cerebro, pero solo los dueños y administradores pueden editarlo.",
    section: {
      couple: "Pareja y fecha",
      itinerary: "Itinerario",
      travel: "Viaje",
      hotels: "Hoteles",
      transport: "Traslados",
      planner: "Coordinador",
      money: "Dinero",
      weather: "Clima y maleta",
      local: "Consejos locales",
      food: "Comida y qué hacer",
      gifts: "Regalos",
      faq: "Preguntas y respuestas",
    } as Record<string, string>,
    fields: {
      names: "Nombres de la pareja",
      wedding_date: "Fecha de la boda (AAAA-MM-DD)",
      location: "Lugar",
      website: "Sitio web de la boda",
      rsvp_link: "Enlace de RSVP",
      name: "Nombre",
      date: "Fecha (AAAA-MM-DD)",
      time: "Hora",
      dress_code: "Código de vestimenta",
      maps_url: "Enlace de Google Maps",
      ceremony_location: "Lugar de la ceremonia",
      ceremony_maps_url: "Maps de la ceremonia",
      reception_location: "Lugar de la recepción",
      reception_maps_url: "Maps de la recepción",
      cost: "Costo",
      description: "Descripción",
      notes: "Notas",
      international: "Vuelos internacionales",
      domestic: "Vuelos nacionales",
      visas: "Visas",
      arrival_advice: "Consejos de llegada",
      hotel: "Hotel",
      recommended: "Recomendado",
      hotel_areas: "Mejores zonas para hospedarse",
      uber: "Apps de transporte",
      taxis: "Taxis",
      service_name: "Servicio recomendado",
      whatsapp: "WhatsApp",
      link: "Enlace",
      planner_name: "Nombre del coordinador",
      helps_with: "En qué ayuda",
      plannerHint: "Cuando el concierge no puede responder algo, dirige a los invitados aquí y la pregunta llega a su lista de pendientes.",
      currency: "Moneda y tarjetas",
      exchange_rate: "Guía de tipo de cambio",
      exchanging: "Dónde cambiar dinero",
      tipping: "Propinas",
      weather: "Clima",
      packing: "Qué empacar",
      grooming: "Cuidado personal y aparatos",
      altitude: "Altitud",
      electricity: "Electricidad y enchufes",
      communication: "Comunicación y tarjetas SIM",
      health_safety: "Salud y seguridad",
      restaurants: "Restaurantes",
      food_to_try: "Comida para probar",
      things_region: "Qué hacer en la región",
      things_local: "Qué ver en la zona",
      gifts: "Regalos y mesa de regalos",
      question: "Pregunta",
      answer: "Respuesta",
    } as Record<string, string>,
    event: (n: number) => `Evento ${n}`,
    addEvent: "Agregar evento",
    addHotel: "Agregar hotel",
    addQa: "Agregar pregunta",
    addItem: "Agregar",
    remove: "Quitar",
    removeConfirm: "¿Quitar esta entrada?",
    oneEntryPerLine: "Una por línea",
    listHint: "Cada línea es una entrada.",
    gapBanner: "Un invitado preguntó esto y su concierge no pudo responder. Agregue la respuesta y publique.",
    versionsTitle: "Historial de versiones",
    liveBadge: "En vivo",
    draftBadge: "Borrador",
    restore: "Restaurar",
    restoreConfirm: (v: number) => `¿Publicar de nuevo la versión ${v}? Los invitados la reciben en menos de un minuto.`,
    restored: (v: number) => `La versión ${v} está en vivo otra vez.`,
    noVersions: "Todavía no hay versiones.",
    askTitle: "Pregunte al concierge",
    modeLive: "Bot en vivo",
    modeDraft: "Mis cambios",
    liveHint: "Esto le pregunta al concierge real que usan sus invitados. Espere un minuto después de publicar.",
    draftHint: "Esto responde con los cambios en su teléfono, antes de publicar nada.",
    askPlaceholder: "Pregunte como lo haría un invitado",
    ask: "Preguntar",
    asking: "Preguntando",
    reply: "Respuesta",
    cancel: "Cancelar",
    yes: "Sí",
  },
};
