export const COPY = {
  en: {
    title: "Messages",
    subtitle: "Every conversation guests have with the concierge, on every channel.",
    filters: { needs_you: "Needs you", all: "All", whatsapp: "WhatsApp", web: "Web", app: "App" } as Record<string, string>,
    channel: { whatsapp: "WhatsApp", web: "Web", app: "App", sms: "SMS" } as Record<string, string>,
    upset: "Upset",
    frustrated: "Frustrated",
    gap: "Could not answer",
    empty: "Nothing here yet.",
    emptyNeedsYou: "Nothing waiting for you.",
    messages: (n: number) => (n === 1 ? "1 message" : `${n} messages`),
    guest: "Guest",
    concierge: "Concierge",
    you: "You",
    waiting: "Waiting for you",
    couldNotAnswer: "The concierge could not answer this.",
    addToBrain: "Add the answer to the brain",
    handled: "Mark handled",
    handledDone: "Marked handled. Nothing waits on this conversation.",
    openEvents: (n: number) => (n === 1 ? "1 open item" : `${n} open items`),
    reply: "Reply",
    replyPlaceholder: "Write your reply",
    sent: (name: string) => `Reply sent. ${name} gets it as a push and in the app.`,
    whatsappHint: "This guest wrote on WhatsApp. Your reply opens WhatsApp so you can send it yourself.",
    openWhatsapp: "Open WhatsApp",
    webHint: "Web visitors have no return channel. The concierge learns the answer when you add it to the brain.",
    viewGuest: "Open guest",
    started: (rel: string) => `Started ${rel}`,
    readOnly: "Read only: owners and admins reply.",
  },
  es: {
    title: "Mensajes",
    subtitle: "Cada conversación de los invitados con el concierge, en todos los canales.",
    filters: { needs_you: "Le necesitan", all: "Todas", whatsapp: "WhatsApp", web: "Web", app: "App" } as Record<string, string>,
    channel: { whatsapp: "WhatsApp", web: "Web", app: "App", sms: "SMS" } as Record<string, string>,
    upset: "Molesto",
    frustrated: "Frustrado",
    gap: "Sin respuesta",
    empty: "Todavía no hay nada aquí.",
    emptyNeedsYou: "Nada esperando por usted.",
    messages: (n: number) => (n === 1 ? "1 mensaje" : `${n} mensajes`),
    guest: "Invitado",
    concierge: "Concierge",
    you: "Usted",
    waiting: "Esperando por usted",
    couldNotAnswer: "El concierge no pudo responder esto.",
    addToBrain: "Agregar la respuesta al cerebro",
    handled: "Marcar como atendida",
    handledDone: "Marcada como atendida. Nada pendiente en esta conversación.",
    openEvents: (n: number) => (n === 1 ? "1 pendiente" : `${n} pendientes`),
    reply: "Responder",
    replyPlaceholder: "Escriba su respuesta",
    sent: (name: string) => `Respuesta enviada. ${name} la recibe como notificación y en la app.`,
    whatsappHint: "Este invitado escribió por WhatsApp. Su respuesta abre WhatsApp para que la envíe usted mismo.",
    openWhatsapp: "Abrir WhatsApp",
    webHint: "Los visitantes web no tienen canal de retorno. El concierge aprende la respuesta cuando la agrega al cerebro.",
    viewGuest: "Ver invitado",
    started: (rel: string) => `Comenzó ${rel}`,
    readOnly: "Solo lectura: los dueños y administradores responden.",
  },
};
