export const COPY = {
  en: {
    menu: "Guest list tools",
    import: "Import guests",
    importSub: "Paste a list or pick a spreadsheet",
    export: "Export to Excel",
    exportSub: "The branded workbook, shared from your phone",
    presets: {
      full: "Full list",
      attending: "Attending only",
      declined: "Declined only",
      pending: "Still to answer",
      contacts: "Contacts",
      per_person: "One row per person",
      dietary: "Dietary notes",
      seating: "Seating",
      event: "By event",
    },
    preparing: "Preparing the file",
    failed: "Could not export.",
    questions: "RSVP questions",
    questionsSub: "What you ask guests when they answer",
  },
  es: {
    menu: "Herramientas de la lista",
    import: "Importar invitados",
    importSub: "Pegue una lista o elija una hoja de cálculo",
    export: "Exportar a Excel",
    exportSub: "El libro con su marca, compartido desde el teléfono",
    presets: {
      full: "Lista completa",
      attending: "Solo confirmados",
      declined: "Solo declinados",
      pending: "Sin responder",
      contacts: "Contactos",
      per_person: "Una fila por persona",
      dietary: "Notas de alimentación",
      seating: "Mesas",
      event: "Por evento",
    },
    preparing: "Preparando el archivo",
    failed: "No se pudo exportar.",
    questions: "Preguntas del RSVP",
    questionsSub: "Lo que pregunta a los invitados al responder",
  },
};
