// Copy for the guest-side wedding site (rendered natively in the app).

const en = {
  title: "The wedding",
  subtitle: "Everything the couple has shared with you.",
  notPublishedTitle: "Not published yet",
  notPublishedBody: "The couple has not published their wedding site yet. Check back soon.",
  errorTitle: "Could not load the site",
  retry: "Try again",
  openFullSite: "See the whole site",
  sections: {
    story: "Our story",
    party: "The wedding party",
    schedule: "The day",
    travel: "Travel and hotels",
    registry: "Gifts",
    faq: "Questions",
    gallery: "Photos",
    video: "Video",
    chat: "Need help?",
    countdown: "Until the big day",
  },
  screens: {
    hotels: "Hotels and travel",
    gifts: "Gifts and registry",
    faq: "Questions",
    gallery: "Photos",
    story: "Our story",
  },
  countdown: { days: "days", hours: "hours", min: "min" },
  today: "Today is the day.",
  kinds: { hotel: "Hotel", venue: "Venue", tip: "Good to know" },
  call: "Call",
  maps: "Maps",
  website: "Website",
  bookingCode: "Booking code",
  copied: "Copied",
  viewRegistry: "Open the registry",
  registryLinkFallback: "Registry",
  chatConcierge: "Ask the concierge",
  chatWhatsapp: "WhatsApp",
  chatPlanner: "Message the planner",
  photoOf: "{n} of {total}",
  close: "Close",
  none: {
    hotels: "The couple has not added travel details yet.",
    gifts: "The couple has not shared gift details yet.",
    faq: "No questions and answers yet. Ask the concierge anything.",
    gallery: "No photos yet.",
    story: "The couple has not written their story yet.",
  },
};

const es: typeof en = {
  title: "La boda",
  subtitle: "Todo lo que la pareja ha compartido con usted.",
  notPublishedTitle: "Todavía no está publicado",
  notPublishedBody: "La pareja todavía no ha publicado su sitio de boda. Vuelva a revisar pronto.",
  errorTitle: "No se pudo cargar el sitio",
  retry: "Intentar de nuevo",
  openFullSite: "Ver el sitio completo",
  sections: {
    story: "Nuestra historia",
    party: "El cortejo",
    schedule: "El día",
    travel: "Viaje y hoteles",
    registry: "Regalos",
    faq: "Preguntas",
    gallery: "Fotos",
    video: "Video",
    chat: "¿Necesita ayuda?",
    countdown: "Para el gran día",
  },
  screens: {
    hotels: "Hoteles y viaje",
    gifts: "Regalos y lista",
    faq: "Preguntas",
    gallery: "Fotos",
    story: "Nuestra historia",
  },
  countdown: { days: "días", hours: "horas", min: "min" },
  today: "Hoy es el día.",
  kinds: { hotel: "Hotel", venue: "Lugar", tip: "Bueno saber" },
  call: "Llamar",
  maps: "Mapa",
  website: "Sitio web",
  bookingCode: "Código de reserva",
  copied: "Copiado",
  viewRegistry: "Abrir la lista de regalos",
  registryLinkFallback: "Lista de regalos",
  chatConcierge: "Preguntar al concierge",
  chatWhatsapp: "WhatsApp",
  chatPlanner: "Escribir al planner",
  photoOf: "{n} de {total}",
  close: "Cerrar",
  none: {
    hotels: "La pareja todavía no ha agregado detalles de viaje.",
    gifts: "La pareja todavía no ha compartido detalles de regalos.",
    faq: "Todavía no hay preguntas y respuestas. Pregúntele lo que quiera al concierge.",
    gallery: "Todavía no hay fotos.",
    story: "La pareja todavía no ha escrito su historia.",
  },
};

export const COPY = { en, es };
export type SiteCopy = typeof en;
