// Day-of runsheet copy, EN and neutral LatAm ES (usted).

export const COPY = {
  en: {
    title: "Day-of runsheet",
    intro:
      "The minute-by-minute schedule for your wedding day. Times are the wedding's own local time.",
    readOnly: "You are viewing the runsheet in read-only mode.",
    emptyTitle: "No runsheet yet",
    emptyHint:
      "Start from a standard wedding-day template and adjust every time to your own plan, or add blocks one by one.",
    template: "Start from a template",
    addBlock: "Add block",
    addCalendar: "Add to calendar",
    editBlock: "Edit block",
    newBlock: "New block",
    day: "Day",
    dayHint: "YYYY-MM-DD",
    start: "Start",
    end: "End",
    endHint: "Optional",
    timeHint: "HH:MM",
    titleField: "Title",
    detail: "Details",
    location: "Location",
    owner: "Who runs it",
    ownerHint: "A name, e.g. the best man or the coordinator",
    vendor: "Vendor",
    noVendor: "No vendor",
    status: "Status",
    statuses: { planned: "Planned", confirmed: "Confirmed", done: "Done" },
    tapStatus: "Tap the status to move it along.",
    save: "Save",
    delete: "Delete",
    deleteConfirm: "Delete this block from the runsheet?",
    cancel: "Cancel",
    blocks: "{n} blocks",
    block: "1 block",
    errorTitle: "The block needs a title.",
    errorDay: "Pick a valid day.",
    errorStart: "Pick a valid start time.",
    error: "Something went wrong. Please try again.",
    pendingDb: "The runsheet is being set up for this wedding.",
  },
  es: {
    title: "Guion del día",
    intro:
      "El programa minuto a minuto de su boda. Las horas son la hora local de la boda.",
    readOnly: "Está viendo el guion en modo de solo lectura.",
    emptyTitle: "Aún no hay guion",
    emptyHint:
      "Empiece desde una plantilla estándar del día de la boda y ajuste cada hora a su plan, o agregue bloques uno por uno.",
    template: "Empezar desde una plantilla",
    addBlock: "Agregar bloque",
    addCalendar: "Agregar al calendario",
    editBlock: "Editar bloque",
    newBlock: "Nuevo bloque",
    day: "Día",
    dayHint: "AAAA-MM-DD",
    start: "Inicio",
    end: "Fin",
    endHint: "Opcional",
    timeHint: "HH:MM",
    titleField: "Título",
    detail: "Detalles",
    location: "Lugar",
    owner: "Quién lo dirige",
    ownerHint: "Un nombre, por ejemplo el padrino o la coordinadora",
    vendor: "Proveedor",
    noVendor: "Sin proveedor",
    status: "Estado",
    statuses: {
      planned: "Planificado",
      confirmed: "Confirmado",
      done: "Hecho",
    },
    tapStatus: "Toque el estado para avanzarlo.",
    save: "Guardar",
    delete: "Eliminar",
    deleteConfirm: "¿Eliminar este bloque del guion?",
    cancel: "Cancelar",
    blocks: "{n} bloques",
    block: "1 bloque",
    errorTitle: "El bloque necesita un título.",
    errorDay: "Elija un día válido.",
    errorStart: "Elija una hora de inicio válida.",
    error: "Algo salió mal. Inténtelo de nuevo.",
    pendingDb: "El guion se está configurando para esta boda.",
  },
};
