// Vendor directory copy, EN and neutral LatAm ES (usted).

const en = {
  title: "Vendors",
  subtitle: "Every vendor, from first call to final payment.",
  pending: "The vendor directory is still being set up for this wedding. Check back shortly.",
  readOnly: "You are viewing the vendor directory in read-only mode.",
  emptyTitle: "No vendors yet",
  emptyBody: "Keep every venue, caterer and photographer you are talking to in one place: contacts, quotes, your private rating and the budget lines each one is tied to.",
  noMatches: "No vendors match.",
  add: "Add vendor",
  edit: "Edit vendor",
  search: "Search name, contact or notes",
  all: "All",
  statVendors: "Vendors",
  statBooked: "Booked",
  statQuoted: "Total quoted",
  categories: {
    venue: "Venue",
    catering: "Catering",
    photo: "Photo",
    video: "Video",
    music: "Music",
    flowers: "Flowers",
    decor: "Decor",
    beauty: "Beauty",
    attire: "Attire",
    cake: "Cake",
    transport: "Transport",
    stationery: "Stationery",
    planner: "Planner",
    rentals: "Rentals",
    other: "Other",
  } as Record<string, string>,
  statuses: { shortlist: "Shortlist", contacted: "Contacted", quoted: "Quoted", booked: "Booked", done: "Done", cancelled: "Cancelled" } as Record<string, string>,
  name: "Vendor name",
  category: "Category",
  status: "Status",
  contactName: "Contact person",
  phone: "Phone",
  email: "Email",
  website: "Website",
  instagram: "Instagram",
  address: "Address",
  priceQuoted: "Quoted price",
  currency: "Currency (3 letters, blank = budget currency)",
  rating: "Your rating",
  notes: "Notes",
  call: "Call",
  whatsapp: "WhatsApp",
  mail: "Email",
  open: "Website",
  linkedItems: "Budget lines",
  linkItem: "Link a budget line",
  unlink: "Unlink",
  noLinked: "No budget line linked yet.",
  noUnlinked: "Every budget line is already linked.",
  tasks: "Tasks",
  save: "Save",
  cancel: "Cancel",
  delete: "Delete vendor",
  deleteBody: "Budget lines and tasks tied to it are kept; only the card goes.",
  confirm: "Confirm",
  offline: "You are offline. Changes need a connection.",
  taskStatus: { open: "Open", in_progress: "In progress", done: "Done" } as Record<string, string>,
};

const es: typeof en = {
  title: "Proveedores",
  subtitle: "Cada proveedor, desde la primera llamada hasta el último pago.",
  pending: "El directorio de proveedores todavía se está preparando para esta boda. Vuelva en un momento.",
  readOnly: "Está viendo el directorio de proveedores en modo de solo lectura.",
  emptyTitle: "Todavía no hay proveedores",
  emptyBody: "Tenga en un solo lugar cada salón, catering y fotógrafo con quien esté hablando: contactos, cotizaciones, su calificación privada y las líneas del presupuesto de cada uno.",
  noMatches: "Ningún proveedor coincide.",
  add: "Agregar proveedor",
  edit: "Editar proveedor",
  search: "Buscar por nombre, contacto o notas",
  all: "Todos",
  statVendors: "Proveedores",
  statBooked: "Contratados",
  statQuoted: "Total cotizado",
  categories: {
    venue: "Salón",
    catering: "Catering",
    photo: "Fotografía",
    video: "Video",
    music: "Música",
    flowers: "Flores",
    decor: "Decoración",
    beauty: "Belleza",
    attire: "Vestuario",
    cake: "Torta",
    transport: "Transporte",
    stationery: "Papelería",
    planner: "Planner",
    rentals: "Alquileres",
    other: "Otro",
  },
  statuses: { shortlist: "Preseleccionado", contacted: "Contactado", quoted: "Cotizado", booked: "Contratado", done: "Finalizado", cancelled: "Cancelado" },
  name: "Nombre del proveedor",
  category: "Categoría",
  status: "Estado",
  contactName: "Persona de contacto",
  phone: "Teléfono",
  email: "Correo",
  website: "Sitio web",
  instagram: "Instagram",
  address: "Dirección",
  priceQuoted: "Precio cotizado",
  currency: "Moneda (3 letras, vacío = moneda del presupuesto)",
  rating: "Su calificación",
  notes: "Notas",
  call: "Llamar",
  whatsapp: "WhatsApp",
  mail: "Correo",
  open: "Sitio web",
  linkedItems: "Líneas del presupuesto",
  linkItem: "Vincular una línea del presupuesto",
  unlink: "Desvincular",
  noLinked: "Todavía no hay líneas vinculadas.",
  noUnlinked: "Todas las líneas del presupuesto ya están vinculadas.",
  tasks: "Tareas",
  save: "Guardar",
  cancel: "Cancelar",
  delete: "Eliminar proveedor",
  deleteBody: "Las líneas del presupuesto y las tareas asociadas se conservan; solo se elimina la ficha.",
  confirm: "Confirmar",
  offline: "Está sin conexión. Los cambios necesitan conexión.",
  taskStatus: { open: "Abierta", in_progress: "En curso", done: "Hecha" },
};

export const COPY = { en, es };
