// Website builder copy, EN and neutral LatAm ES (usted).

export const COPY = {
  en: {
    title: "Wedding website",
    subtitle: "Everything guests see at your address.",
    published: "Live",
    draft: "Draft",
    address: "Address",
    addressHint: "app.guest-ly.com/",
    changeAddress: "Change address",
    addressPlaceholder: "sofia-y-mateo",
    save: "Save",
    saving: "Saving",
    saved: "Saved",
    cancel: "Cancel",
    done: "Done",
    remove: "Remove",
    add: "Add",
    up: "Move up",
    down: "Move down",
    preview: "Preview",
    openSite: "Open the site",
    copyLink: "Copy link",
    copied: "Link copied",
    share: "Share",
    publish: "Publish",
    unpublish: "Take offline",
    publishConfirm: "Publish the website? Guests with the link will see it right away.",
    unpublishConfirm: "Take the website offline? The link will stop working until you publish again.",
    privacy: "Privacy",
    password: "Password",
    passwordOn: "Guests need a password",
    passwordOff: "Anyone with the link can open it",
    setPassword: "Set a password",
    newPassword: "New password (4 to 72 characters)",
    removePassword: "Remove password",
    noindex: "Hide from search engines",
    noindexHint: "Google and others will not list the site.",
    theme: "Look",
    themes: { night: "Night", ivory: "Ivory", gold: "Gold" },
    sections: "Sections",
    sectionsHint: "Switch sections on or off and drag the order with the arrows. The hero always comes first.",
    custom: "Your own sections",
    customHint: "Free text blocks shown after the sections above.",
    details: "Details",
    detailsHint: "Search title, description, hashtag.",
    inherited: "From the Wedding Brain",
    inheritedHint: "Names, date, city, events and answers come from the Brain. Edit them there; here you only style how they show.",
    pending: "The website is being set up for this wedding. Try again in a moment.",
    en: "English",
    es: "Spanish",
    section: {
      hero: "Cover",
      countdown: "Countdown",
      story: "Our story",
      gallery: "Gallery",
      video: "Video",
      schedule: "The day",
      travel: "Travel and stay",
      registry: "Registry",
      party: "Wedding party",
      faq: "Questions",
      rsvp: "RSVP",
      chat: "Ask the assistant",
    },
    fields: {
      heading: "Heading",
      body: "Text",
      names: "Names as shown",
      tagline: "Tagline",
      showDate: "Show the date",
      showCity: "Show the city",
      photo: "Photo",
      choosePhoto: "Choose a photo",
      replacePhoto: "Replace photo",
      removePhoto: "Remove photo",
      uploading: "Uploading",
      accentPhoto: "Accent photo",
      images: "Photos",
      addImages: "Add photos",
      caption: "Caption",
      videoUrl: "YouTube or Vimeo link",
      videoHint: "Paste a youtube.com, youtu.be or vimeo.com link.",
      showPrivate: "Show invitation-only events to everyone",
      events: "Events",
      hidden: "Hidden on the site",
      overrideTitle: "Title on the site",
      note: "Note under the event",
      items: "Places",
      addItem: "Add a place",
      kind: "Type",
      kinds: { hotel: "Hotel", venue: "Venue", tip: "Tip" },
      address: "Address",
      phone: "Phone",
      url: "Website link",
      mapUrl: "Map link",
      promo: "Promo code",
      registryMode: "Where gifts go",
      registryModes: { external: "Link to a registry", page: "A page on this site", hidden: "Only the note" },
      externalUrl: "Registry link",
      registryItems: "Blocks on the registry page",
      addRegistryItem: "Add a block",
      registryKinds: { link: "Link", note: "Note", image: "Image" },
      members: "People",
      addMember: "Add a person",
      name: "Name",
      role: "Role",
      bio: "A few words",
      hideFacts: "Hide the Brain's answers, show only these",
      faqItems: "Extra questions",
      addFaq: "Add a question",
      question: "Question",
      answer: "Answer",
      questionsNote: "RSVP questions are edited under RSVPs.",
      whatsapp: "WhatsApp button",
      whatsappNumber: "Number with country code",
      prefill: "Opening message",
      planner: "Planner button",
      plannerName: "Planner name",
      seoTitle: "Browser title",
      seoDescription: "Description for links",
      hashtag: "Hashtag in the footer",
      customHeading: "Heading",
      addCustom: "Add a section",
      enabled: "Shown on the site",
    },
    errors: {
      tooBig: "That photo is too large. Choose one under 4 MB.",
      pickFailed: "Could not open your photos.",
    },
  },
  es: {
    title: "Sitio web de la boda",
    subtitle: "Todo lo que los invitados ven en su dirección.",
    published: "Publicado",
    draft: "Borrador",
    address: "Dirección",
    addressHint: "app.guest-ly.com/",
    changeAddress: "Cambiar dirección",
    addressPlaceholder: "sofia-y-mateo",
    save: "Guardar",
    saving: "Guardando",
    saved: "Guardado",
    cancel: "Cancelar",
    done: "Listo",
    remove: "Quitar",
    add: "Agregar",
    up: "Subir",
    down: "Bajar",
    preview: "Vista previa",
    openSite: "Abrir el sitio",
    copyLink: "Copiar enlace",
    copied: "Enlace copiado",
    share: "Compartir",
    publish: "Publicar",
    unpublish: "Desactivar",
    publishConfirm: "¿Publicar el sitio? Los invitados con el enlace lo verán de inmediato.",
    unpublishConfirm: "¿Desactivar el sitio? El enlace dejará de funcionar hasta que vuelva a publicar.",
    privacy: "Privacidad",
    password: "Contraseña",
    passwordOn: "Los invitados necesitan una contraseña",
    passwordOff: "Cualquiera con el enlace puede abrirlo",
    setPassword: "Definir una contraseña",
    newPassword: "Nueva contraseña (de 4 a 72 caracteres)",
    removePassword: "Quitar la contraseña",
    noindex: "Ocultar de los buscadores",
    noindexHint: "Google y otros no mostrarán el sitio.",
    theme: "Estilo",
    themes: { night: "Noche", ivory: "Marfil", gold: "Dorado" },
    sections: "Secciones",
    sectionsHint: "Active o desactive secciones y cambie el orden con las flechas. La portada siempre va primero.",
    custom: "Sus propias secciones",
    customHint: "Bloques de texto libre que aparecen después de las secciones de arriba.",
    details: "Detalles",
    detailsHint: "Título para buscadores, descripción, hashtag.",
    inherited: "Desde el Cerebro de la boda",
    inheritedHint: "Nombres, fecha, ciudad, eventos y respuestas vienen del Cerebro. Edítelos allí; aquí solo decide cómo se muestran.",
    pending: "El sitio se está preparando para esta boda. Inténtelo de nuevo en un momento.",
    en: "Inglés",
    es: "Español",
    section: {
      hero: "Portada",
      countdown: "Cuenta regresiva",
      story: "Nuestra historia",
      gallery: "Galería",
      video: "Video",
      schedule: "El gran día",
      travel: "Cómo llegar y dónde quedarse",
      registry: "Mesa de regalos",
      party: "Cortejo",
      faq: "Preguntas",
      rsvp: "Confirmación",
      chat: "Pregunte al asistente",
    },
    fields: {
      heading: "Título",
      body: "Texto",
      names: "Nombres como se muestran",
      tagline: "Frase",
      showDate: "Mostrar la fecha",
      showCity: "Mostrar la ciudad",
      photo: "Foto",
      choosePhoto: "Elegir una foto",
      replacePhoto: "Reemplazar foto",
      removePhoto: "Quitar foto",
      uploading: "Subiendo",
      accentPhoto: "Foto de acento",
      images: "Fotos",
      addImages: "Agregar fotos",
      caption: "Pie de foto",
      videoUrl: "Enlace de YouTube o Vimeo",
      videoHint: "Pegue un enlace de youtube.com, youtu.be o vimeo.com.",
      showPrivate: "Mostrar a todos los eventos por invitación",
      events: "Eventos",
      hidden: "Oculto en el sitio",
      overrideTitle: "Título en el sitio",
      note: "Nota debajo del evento",
      items: "Lugares",
      addItem: "Agregar un lugar",
      kind: "Tipo",
      kinds: { hotel: "Hotel", venue: "Lugar", tip: "Consejo" },
      address: "Dirección",
      phone: "Teléfono",
      url: "Enlace del sitio",
      mapUrl: "Enlace del mapa",
      promo: "Código promocional",
      registryMode: "A dónde van los regalos",
      registryModes: { external: "Enlace a una mesa de regalos", page: "Una página en este sitio", hidden: "Solo la nota" },
      externalUrl: "Enlace de la mesa de regalos",
      registryItems: "Bloques de la página de regalos",
      addRegistryItem: "Agregar un bloque",
      registryKinds: { link: "Enlace", note: "Nota", image: "Imagen" },
      members: "Personas",
      addMember: "Agregar una persona",
      name: "Nombre",
      role: "Rol",
      bio: "Unas palabras",
      hideFacts: "Ocultar las respuestas del Cerebro y mostrar solo estas",
      faqItems: "Preguntas adicionales",
      addFaq: "Agregar una pregunta",
      question: "Pregunta",
      answer: "Respuesta",
      questionsNote: "Las preguntas de confirmación se editan en Confirmaciones.",
      whatsapp: "Botón de WhatsApp",
      whatsappNumber: "Número con código de país",
      prefill: "Mensaje inicial",
      planner: "Botón del planner",
      plannerName: "Nombre del planner",
      seoTitle: "Título en el navegador",
      seoDescription: "Descripción para enlaces",
      hashtag: "Hashtag en el pie",
      customHeading: "Título",
      addCustom: "Agregar una sección",
      enabled: "Se muestra en el sitio",
    },
    errors: {
      tooBig: "Esa foto es demasiado grande. Elija una de menos de 4 MB.",
      pickFailed: "No se pudieron abrir sus fotos.",
    },
  },
};
