// Seating copy, EN and neutral LatAm ES (tú).

export const COPY = {
  en: {
    title: "Seating",
    subtitle: "Give every guest a seat at the right table.",
    allSeated: "Everyone confirmed has a seat.",
    stats: {
      seated: "seated",
      unseated: "still unseated",
      free: "free seats",
      tables: "tables",
    },
    tables: "Tables",
    noTables:
      "No tables yet. Add them one by one, or let the concierge suggest a layout from your numbers.",
    addTable: "Add a table",
    tableName: "Table name",
    tableNamePlaceholder: "Table 1",
    seats: "Seats",
    shape: "Shape",
    round: "Round",
    rect: "Rectangular",
    seatedOf: "{seated} of {capacity} seated",
    overCapacity: "Over capacity",
    unseated: "Still unseated",
    unseatedHint: "Tap a party to give it a table.",
    unconfirmed: "Not confirmed yet",
    unconfirmedHint:
      "Parties without an attending answer. You can seat them from an estimate.",
    showUnconfirmed: "Show unconfirmed parties",
    people: "{n} people",
    person: "1 person",
    pickTable: "Pick a table for {name}",
    noRoom: "{free} free",
    assign: "Seat here",
    remove: "Remove from table",
    removeParty: "Unseat the whole party",
    atTable: "At {table}",
    splitAcross: "Split across {n} tables",
    savePlan: "Save plan",
    saved: "Plan saved",
    discardTitle: "Unsaved changes",
    discardBody: "You changed the seating and have not saved. Leave anyway?",
    keepEditing: "Keep editing",
    discard: "Discard changes",
    deleteTable: "Delete table",
    deleteTableBody: "The people at {table} will be unseated. Delete it?",
    delete: "Delete",
    cancel: "Cancel",
    suggest: "Suggest seating",
    suggestIntro:
      "The same deterministic rule the web uses: parties stay together, then relationship, tags and surname decide who sits near whom. Nothing already seated moves.",
    criteria: "Priority",
    criteriaHint: "Tap to move a rule up.",
    criterion: {
      party: "Groups",
      relationship: "Relationship",
      tags: "Tags",
      surname: "Surnames",
    },
    includeUnconfirmed: "Include unconfirmed parties",
    preview: "Preview",
    apply: "Apply this seating",
    placed: "{n} parties placed at {t} tables",
    unplaced: "{n} parties could not be placed",
    warnings: "Notes",
    floorPlan: "Floor plan",
    floorPlanIntro:
      "A photo or screenshot of the venue's plan. The concierge reads it and finds the tables for you.",
    takePhoto: "Take a photo",
    pickPhoto: "Choose from library",
    uploading: "Uploading your plan",
    readPlan: "Read the plan",
    readPlanHint:
      "Finds the tables on the photo and adds them as drafts. Existing tables stay where they are. Can take up to two minutes.",
    reading: "Reading the plan",
    readDone: "{n} tables found on the plan.",
    noPlan: "No floor plan yet.",
    confidence: "{pct}% sure",
    confirmTable: "Looks right",
    draft: "Draft",
    manual: "Manual",
    fromPlan: "From the plan",
    readOnly: "You are viewing the seating in read-only mode.",
    empty: "The couple has not started seating yet.",
    error: "Something went wrong. Please try again.",
    photoDenied: "Guest-ly needs access to your photos for this.",
    cameraDenied: "Guest-ly needs the camera for this.",
  },
  es: {
    title: "Mesas",
    subtitle: "Da a cada invitado un asiento en la mesa correcta.",
    allSeated: "Todos los confirmados tienen asiento.",
    stats: {
      seated: "sentados",
      unseated: "sin asiento",
      free: "asientos libres",
      tables: "mesas",
    },
    tables: "Mesas",
    noTables:
      "Aún no hay mesas. Agrégalas una por una, o deja que el concierge sugiera una distribución según tus números.",
    addTable: "Agregar una mesa",
    tableName: "Nombre de la mesa",
    tableNamePlaceholder: "Mesa 1",
    seats: "Asientos",
    shape: "Forma",
    round: "Redonda",
    rect: "Rectangular",
    seatedOf: "{seated} de {capacity} sentados",
    overCapacity: "Sobre capacidad",
    unseated: "Sin asiento",
    unseatedHint: "Toque un grupo para asignarle una mesa.",
    unconfirmed: "Aún sin confirmar",
    unconfirmedHint:
      "Grupos sin respuesta de asistencia. Puedes sentarlos a partir de una estimación.",
    showUnconfirmed: "Mostrar grupos sin confirmar",
    people: "{n} personas",
    person: "1 persona",
    pickTable: "Elige una mesa para {name}",
    noRoom: "{free} libres",
    assign: "Sentar aquí",
    remove: "Quitar de la mesa",
    removeParty: "Quitar a todo el grupo",
    atTable: "En {table}",
    splitAcross: "Repartido en {n} mesas",
    savePlan: "Guardar plan",
    saved: "Plan guardado",
    discardTitle: "Cambios sin guardar",
    discardBody:
      "Cambiaste la distribución y no la has guardado. ¿Salir de todos modos?",
    keepEditing: "Seguir editando",
    discard: "Descartar cambios",
    deleteTable: "Eliminar mesa",
    deleteTableBody:
      "Las personas de {table} quedarán sin asiento. ¿Eliminarla?",
    delete: "Eliminar",
    cancel: "Cancelar",
    suggest: "Sugerir distribución",
    suggestIntro:
      "La misma regla determinista de la web: los grupos no se separan, y luego la relación, las etiquetas y el apellido deciden quién se sienta cerca de quién. Nadie ya sentado se mueve.",
    criteria: "Prioridad",
    criteriaHint: "Toque para subir una regla.",
    criterion: {
      party: "Grupos",
      relationship: "Relación",
      tags: "Etiquetas",
      surname: "Apellidos",
    },
    includeUnconfirmed: "Incluir grupos sin confirmar",
    preview: "Vista previa",
    apply: "Aplicar esta distribución",
    placed: "{n} grupos ubicados en {t} mesas",
    unplaced: "{n} grupos no se pudieron ubicar",
    warnings: "Notas",
    floorPlan: "Plano del salón",
    floorPlanIntro:
      "Una foto o captura del plano del lugar. El concierge lo lee y encuentra las mesas por ti.",
    takePhoto: "Tomar una foto",
    pickPhoto: "Elegir de la galería",
    uploading: "Subiendo tu plano",
    readPlan: "Leer el plano",
    readPlanHint:
      "Encuentra las mesas en la foto y las agrega como borradores. Las mesas existentes no se mueven. Puede tardar hasta dos minutos.",
    reading: "Leyendo el plano",
    readDone: "{n} mesas encontradas en el plano.",
    noPlan: "Aún no hay plano.",
    confidence: "{pct}% de certeza",
    confirmTable: "Está bien",
    draft: "Borrador",
    manual: "Manual",
    fromPlan: "Del plano",
    readOnly: "Estás viendo la distribución en modo de solo lectura.",
    empty: "La pareja aún no ha empezado la distribución de mesas.",
    error: "Algo salió mal. Inténtalo de nuevo.",
    photoDenied: "Guest-ly necesita acceso a tus fotos para esto.",
    cameraDenied: "Guest-ly necesita la cámara para esto.",
  },
};
