// Couple surface copy for build 12 (v1.2): the five tabs (Inicio, Invitados,
// Mensajes, Plan, Más), the guest card, add guest and the merged reminders.
// Spanish uses tú. No em or en dashes.

const plural = (n: number, one: string, other: string) => (n === 1 ? one : other).replace("{n}", String(n));

export const COPY = {
  en: {
    tabs: { home: "Home", guests: "Guests", messages: "Messages", plan: "Plan", more: "More" },
    home: {
      yourWedding: "Your wedding",
      days: (n: number) => plural(n, "{n} day", "{n} days"),
      replied: (a: number, b: number) => `${a} of ${b}`,
      repliedWord: "replied",
      deadline: (d: string) => `Deadline: ${d}`,
      noDeadline: "Tap to see every reply",
      going: "Going",
      notGoing: "Not going",
      pending: "Pending",
      quick: "Quick actions",
      addGuest: "Add guest",
      share: "Share invite",
      announce: "Send announcement",
      reminders: "Reminders",
      remindersCount: (n: number) => `Reminders (${n})`,
      noReminders: "No reminders right now",
      noRemindersBody: "We will let you know when something comes in.",
      ask: "Ask your Coordinator",
      askBody: "Knows your list, your budget and what is left.",
      dayOf: "Wedding day mode is on",
      dayOfBody: "Door check-in and the day's schedule are one tap away.",
    },
    guests: {
      title: "Guests",
      subtitle: (total: number, replied: number) => `${plural(total, "{n} party", "{n} parties")} · ${replied} replied`,
      search: "Search by name",
      filters: { all: "All", pending: "Pending", attending: "Going", declined: "Not going", changed: "Changed" },
      sendReminder: "Send reminder",
      moreOptions: "More options",
      add: "Add guest",
      going: (n: number) => (n > 1 ? `Going, party of ${n}` : "Going"),
      declined: (n: number) => (n > 1 ? `Not going · ${n} people` : "Not going"),
      pendingRow: (n: number) => (n > 1 ? `Pending · ${n} people` : "Pending"),
      changed: "Changed",
      remindTitle: (n: number) => plural(n, "{n} party has not replied", "{n} parties have not replied"),
      remindDeadline: (d: string) => `The deadline is ${d}.`,
      remindNoDeadline: "A friendly nudge usually brings replies in.",
      remindWithPhone: (n: number) => `Remind ${n} with a phone`,
      remindPending: (n: number) => `Remind ${n} pending`,
      withoutPhone: (n: number) => `${n} without a phone`,
      addPhones: "Add",
      noPhoneTitle: (n: number) => `${n} without a phone`,
      noPhoneBody: "With a phone they get the WhatsApp reminder. Tap someone to add it.",
      remindSentTitle: "Reminder sent",
      noResultTitle: (q: string) => `Nobody called "${q}" on your list`,
      noResultBody: "Check the spelling or add this person.",
      addNamed: (q: string) => `Add ${q}`,
      filterEmpty: "Nobody in this filter",
      menuTitle: "Guests",
      menu: {
        import: "Import list",
        importSub: "Excel or CSV",
        export: "Export",
        exportSub: "Excel with every party",
        questions: "RSVP questions",
        questionsSub: "Meal, allergies, song",
        auto: "Automatic reminders",
        autoOn: "On",
        autoOff: "Off",
        share: "Share invitation",
        shareSub: "Link and code for your guests",
      },
      exportTitle: "Export",
    },
    card: {
      title: "Guest card",
      repliedOn: (when: string, via: string) => (via ? `Replied ${when} · ${via}` : `Replied ${when}`),
      noReply: "No reply yet",
      noReplyDeadline: (d: string) => `No reply yet · deadline ${d}`,
      changedPill: "Changed their reply",
      party: (n: number) => `Party (${n})`,
      contact: "Contact",
      phoneSub: "Phone and WhatsApp",
      emailSub: "Email",
      addPhone: "Add phone",
      addPhoneSub: "Without a phone, reminders cannot reach them",
      contactHidden: "Contact details are hidden for your role",
      history: "History",
      historyReplied: "Replied",
      historyReminded: "Reminder sent",
      historyAdded: "Added to your list",
      historyCheckedIn: "Checked in at the door",
      language: (l: string) => `Language: ${l}`,
      langs: { en: "English", es: "Spanish" } as Record<string, string>,
      table: (t: string) => `Table ${t}`,
      noTable: "No table yet",
      tableSub: "Tap to open Seating",
      answers: "Their answers",
      notes: "Notes",
      guestNote: (name: string) => `Note from ${name}`,
      editGuest: "Edit guest",
      editRsvp: "Edit RSVP",
      message: "Message",
      seat: "Seat",
      member: { going: "Going", notGoing: "Not going", pending: "Pending" },
      saved: "Saved",
      rsvpSaved: "RSVP saved",
      noThread: "This guest has not written yet. Send them an announcement from Messages.",
    },
    add: {
      title: "New guest",
      name: "Name",
      namePlaceholder: "First and last name",
      nameError: "Add their name",
      phone: "Phone",
      phonePlaceholder: "With country code, for example +52 646 555 1234",
      phoneHint: "WhatsApp messages reach them here.",
      phoneError: "Check the number: some digits are missing",
      more: "More details",
      plusOnes: "Plus-ones",
      plusOnesSub: "People coming in their party",
      fewer: "One fewer",
      more1: "One more",
      members: "Their names, one per line",
      email: "Email",
      language: "Language for their messages",
      notes: "Notes",
      notesPlaceholder: "Only you and your planner see them",
      added: "Guest added.",
      view: "View",
      discardTitle: "Discard this guest?",
      discardBody: "What you typed will be lost.",
    },
    messages: {
      title: "Messages",
      conversations: "Conversations",
      announcements: "Announcements",
      compose: "Compose",
      composeAnnouncement: "Announcement to guests",
      composeAnnouncementSub: "To everyone or to a group",
      composeOne: "Message to one guest",
      composeOneSub: "Pick who",
      pickTitle: "Message to one guest",
      pickSearch: "Search by name",
      pickNoThread: (name: string) => `${name} has not written yet, so there is no conversation to answer. Send them an announcement instead.`,
      pickWhatsApp: "Open WhatsApp",
      pickAnnounce: "Send an announcement",
      unanswered: (n: number) => plural(n, "1 question your concierge could not answer", "{n} questions your concierge could not answer"),
      teach: "Teach it",
      answered: "Nothing is waiting for you",
      answeredSub: "See what your concierge answers",
      newAnnouncement: "New announcement",
      exactCount: "The number you confirm is exactly who it goes to.",
      noAnnouncements: "No announcements yet",
      noAnnouncementsBody: "Send a save the date, a reminder or news to everyone or to a group.",
      filters: { all: "All", needs_you: "Needs you", whatsapp: "WhatsApp", web: "Web", app: "App" } as Record<string, string>,
      showing: (what: string) => `Showing: ${what}`,
      showAll: "See all",
      you: "You: ",
    },
    thread: {
      viewCard: "View card",
      fromConcierge: "from the concierge",
      sending: "Sending...",
      delivered: "Delivered",
      openedWhatsapp: "Opened in WhatsApp",
      failed: "Not sent. Tap to try again.",
      replyApp: "Reply in the app",
      replyWhatsapp: "Reply on WhatsApp",
      emptyTitle: (name: string) => `Write to ${name}`,
    },
    plan: {
      title: "Plan",
      daysLeft: (n: number) => plural(n, "1 day to go", "{n} days to go"),
      coordinator: "Coordinator",
      budget: "Budget",
      budgetNum: (n: number) => `${n}% paid`,
      tasks: "Tasks",
      tasksWeek: (n: number) => `${n} this week`,
      tasksOpen: (n: number) => `${n} open`,
      tasksDone: "All done",
      seating: "Seating",
      seatingNum: (n: number) => `${n} unseated`,
      seatingDone: "Everyone seated",
      runsheet: "Day-of schedule",
      runsheetNum: (n: number) => plural(n, "1 block", "{n} blocks"),
      runsheetNone: "Not started",
      budgetNone: "No budget yet",
      tasksSee: "See tasks",
      seatingNone: "No tables yet",
    },
    more: {
      title: "More",
      code: "Invitation code",
      share: "Share",
      site: "Wedding site",
      brain: "What your concierge knows",
      brainSub: "The answers it gives your guests",
      coordinator: "Coordinator",
      coordinatorSub: "Ask anything about your wedding",
      checkin: "Door check-in",
      checkinSub: "Check guests in at the door",
      dayof: "Wedding day mode",
      dayofSub: "Now, next and who is in",
      requests: "Planner requests",
      requestsSub: "Changes your planner asks you to approve",
      insights: "Concierge insights",
      insightsSub: "What guests ask most",
      guide: "Guide",
      guideSub: "How each part works",
      settings: "Settings",
      settingsSub: "Account, notifications, reminders, your partner",
    },
    budget: {
      vendors: "Vendors",
      vendorsSub: "Every vendor you work with",
      allVendors: (n: number) => plural(n, "See your vendor", "See all {n} vendors"),
      linkedVendors: "Vendors in this budget",
      vendor: "Vendor",
      linkVendor: "Link a vendor",
      newVendor: "New vendor",
      noVendors: "No vendors yet. Add one and link it to this line.",
      openVendor: "Open vendor",
    },
    shareText: (names: string, url: string, code: string) => `${names ? `${names} invite you. ` : ""}Reply here: ${url} (code ${code})`,
  },
  es: {
    tabs: { home: "Inicio", guests: "Invitados", messages: "Mensajes", plan: "Plan", more: "Más" },
    home: {
      yourWedding: "Tu boda",
      days: (n: number) => plural(n, "{n} día", "{n} días"),
      replied: (a: number, b: number) => `${a} de ${b}`,
      repliedWord: "respondieron",
      deadline: (d: string) => `Fecha límite: ${d}`,
      noDeadline: "Toca para ver cada respuesta",
      going: "Van",
      notGoing: "No van",
      pending: "Pendientes",
      quick: "Acciones rápidas",
      addGuest: "Agregar invitado",
      share: "Compartir invitación",
      announce: "Mandar aviso",
      reminders: "Recordatorios",
      remindersCount: (n: number) => `Recordatorios (${n})`,
      noReminders: "No tienes recordatorios",
      noRemindersBody: "Te avisamos cuando llegue algo.",
      ask: "Pregúntale a tu Coordinador",
      askBody: "Sabe tu lista, tu presupuesto y lo que falta.",
      dayOf: "El modo día de la boda está encendido",
      dayOfBody: "La recepción en la puerta y el itinerario del día están a un toque.",
    },
    guests: {
      title: "Invitados",
      subtitle: (total: number, replied: number) => `${plural(total, "{n} grupo", "{n} grupos")} · ${replied} respondieron`,
      search: "Buscar por nombre",
      filters: { all: "Todos", pending: "Pendientes", attending: "Van", declined: "No van", changed: "Cambiaron" },
      sendReminder: "Mandar recordatorio",
      moreOptions: "Más opciones",
      add: "Agregar invitado",
      going: (n: number) => (n > 1 ? `Va con ${n}` : "Va"),
      declined: (n: number) => (n > 1 ? `No van · ${n} personas` : "No va"),
      pendingRow: (n: number) => (n > 1 ? `Pendiente · ${n} personas` : "Pendiente"),
      changed: "Cambió",
      remindTitle: (n: number) => plural(n, "{n} grupo sin responder", "{n} grupos sin responder"),
      remindDeadline: (d: string) => `La fecha límite es el ${d}.`,
      remindNoDeadline: "Un recordatorio amable suele traer respuestas.",
      remindWithPhone: (n: number) => `Recordar a ${n} con teléfono`,
      remindPending: (n: number) => `Recordar a ${n} pendientes`,
      withoutPhone: (n: number) => `${n} sin teléfono`,
      addPhones: "Agregar",
      noPhoneTitle: (n: number) => `${n} sin teléfono`,
      noPhoneBody: "Con su teléfono les llega el recordatorio por WhatsApp. Toca a alguien para agregarlo.",
      remindSentTitle: "Recordatorio enviado",
      noResultTitle: (q: string) => `Nadie se llama "${q}" en tu lista`,
      noResultBody: "Revisa cómo se escribe o agrega a esta persona.",
      addNamed: (q: string) => `Agregar a ${q}`,
      filterEmpty: "Nadie en este filtro",
      menuTitle: "Invitados",
      menu: {
        import: "Importar lista",
        importSub: "Excel o CSV",
        export: "Exportar",
        exportSub: "Excel con todos los grupos",
        questions: "Preguntas del RSVP",
        questionsSub: "Comida, alergias, canción",
        auto: "Recordatorios automáticos",
        autoOn: "Encendidos",
        autoOff: "Apagados",
        share: "Compartir invitación",
        shareSub: "Enlace y código para tus invitados",
      },
      exportTitle: "Exportar",
    },
    card: {
      title: "Ficha del invitado",
      repliedOn: (when: string, via: string) => (via ? `Respondió ${when} · ${via}` : `Respondió ${when}`),
      noReply: "Todavía no responde",
      noReplyDeadline: (d: string) => `Todavía no responde · fecha límite ${d}`,
      changedPill: "Cambió su respuesta",
      party: (n: number) => `Grupo (${n})`,
      contact: "Contacto",
      phoneSub: "Teléfono y WhatsApp",
      emailSub: "Correo",
      addPhone: "Agregar teléfono",
      addPhoneSub: "Sin teléfono no le llegan recordatorios",
      contactHidden: "Los datos de contacto están ocultos para tu rol",
      history: "Historial",
      historyReplied: "Respondió",
      historyReminded: "Recordatorio enviado",
      historyAdded: "Agregado a tu lista",
      historyCheckedIn: "Entró por la puerta",
      language: (l: string) => `Idioma: ${l}`,
      langs: { en: "Inglés", es: "Español" } as Record<string, string>,
      table: (t: string) => `Mesa ${t}`,
      noTable: "Sin mesa todavía",
      tableSub: "Toca para abrir Mesas",
      answers: "Sus respuestas",
      notes: "Notas",
      guestNote: (name: string) => `Nota de ${name}`,
      editGuest: "Editar invitado",
      editRsvp: "Editar respuesta",
      message: "Mensaje",
      seat: "Mesa",
      member: { going: "Va", notGoing: "No va", pending: "Pendiente" },
      saved: "Guardado",
      rsvpSaved: "Respuesta guardada",
      noThread: "Este invitado todavía no te escribe. Mándale un aviso desde Mensajes.",
    },
    add: {
      title: "Nuevo invitado",
      name: "Nombre",
      namePlaceholder: "Nombre y apellido",
      nameError: "Escribe su nombre",
      phone: "Teléfono",
      phonePlaceholder: "Con lada del país, por ejemplo +52 646 555 1234",
      phoneHint: "Por aquí le llegan los avisos de WhatsApp.",
      phoneError: "Revisa el número: faltan dígitos",
      more: "Más detalles",
      plusOnes: "Acompañantes",
      plusOnesSub: "Personas que vienen en su grupo",
      fewer: "Uno menos",
      more1: "Uno más",
      members: "Sus nombres, uno por línea",
      email: "Correo",
      language: "Idioma de sus mensajes",
      notes: "Notas",
      notesPlaceholder: "Solo las ven tú y tu planner",
      added: "Invitado agregado.",
      view: "Ver",
      discardTitle: "¿Descartar este invitado?",
      discardBody: "Lo que escribiste se pierde.",
    },
    messages: {
      title: "Mensajes",
      conversations: "Conversaciones",
      announcements: "Avisos",
      compose: "Redactar",
      composeAnnouncement: "Aviso a invitados",
      composeAnnouncementSub: "Para todos o para un grupo",
      composeOne: "Mensaje a un invitado",
      composeOneSub: "Elige a quién",
      pickTitle: "Mensaje a un invitado",
      pickSearch: "Buscar por nombre",
      pickNoThread: (name: string) => `${name} todavía no te escribe, así que no hay conversación que contestar. Mándale un aviso.`,
      pickWhatsApp: "Abrir WhatsApp",
      pickAnnounce: "Mandar un aviso",
      unanswered: (n: number) => plural(n, "1 pregunta que el concierge no supo responder", "{n} preguntas que el concierge no supo responder"),
      teach: "Enséñale",
      answered: "Nada espera tu respuesta",
      answeredSub: "Mira lo que contesta tu concierge",
      newAnnouncement: "Nuevo aviso",
      exactCount: "El número que confirmas es exactamente a quién se envía.",
      noAnnouncements: "Todavía no mandas avisos",
      noAnnouncementsBody: "Manda un guarda la fecha, un recordatorio o una novedad a todos o a un grupo.",
      filters: { all: "Todas", needs_you: "Te necesitan", whatsapp: "WhatsApp", web: "Web", app: "App" } as Record<string, string>,
      showing: (what: string) => `Mostrando: ${what}`,
      showAll: "Ver todas",
      you: "Tú: ",
    },
    thread: {
      viewCard: "Ver ficha",
      fromConcierge: "lo pasó el concierge",
      sending: "Enviando...",
      delivered: "Entregado",
      openedWhatsapp: "Abierto en WhatsApp",
      failed: "No se envió. Toca para intentar otra vez.",
      replyApp: "Responder en la app",
      replyWhatsapp: "Responder por WhatsApp",
      emptyTitle: (name: string) => `Escríbele a ${name}`,
    },
    plan: {
      title: "Plan",
      daysLeft: (n: number) => plural(n, "Falta 1 día", "Faltan {n} días"),
      coordinator: "Coordinador",
      budget: "Presupuesto",
      budgetNum: (n: number) => `${n}% pagado`,
      tasks: "Tareas",
      tasksWeek: (n: number) => `${n} esta semana`,
      tasksOpen: (n: number) => plural(n, "1 pendiente", "{n} pendientes"),
      tasksDone: "Todo listo",
      seating: "Mesas",
      seatingNum: (n: number) => `${n} sin mesa`,
      seatingDone: "Todos tienen mesa",
      runsheet: "Itinerario del día",
      runsheetNum: (n: number) => plural(n, "1 bloque", "{n} bloques"),
      runsheetNone: "Sin armar",
      budgetNone: "Sin presupuesto",
      tasksSee: "Ver tareas",
      seatingNone: "Sin mesas todavía",
    },
    more: {
      title: "Más",
      code: "Código de invitación",
      share: "Compartir",
      site: "Sitio de la boda",
      brain: "Lo que sabe tu concierge",
      brainSub: "Lo que responde a tus invitados",
      coordinator: "Coordinador",
      coordinatorSub: "Pregúntale lo que sea de tu boda",
      checkin: "Recepción en la puerta",
      checkinSub: "Registra a tus invitados al llegar",
      dayof: "Modo día de la boda",
      dayofSub: "Ahora, lo que sigue y quién ya llegó",
      requests: "Solicitudes del planner",
      requestsSub: "Cambios que tu planner te pide aprobar",
      insights: "Lo que preguntan tus invitados",
      insightsSub: "Las preguntas más frecuentes",
      guide: "Guía",
      guideSub: "Cómo funciona cada parte",
      settings: "Ajustes",
      settingsSub: "Cuenta, notificaciones, recordatorios, tu pareja",
    },
    budget: {
      vendors: "Proveedores",
      vendorsSub: "Todos los proveedores con los que trabajas",
      allVendors: (n: number) => plural(n, "Ver tu proveedor", "Ver los {n} proveedores"),
      linkedVendors: "Proveedores de este presupuesto",
      vendor: "Proveedor",
      linkVendor: "Vincular un proveedor",
      newVendor: "Nuevo proveedor",
      noVendors: "Todavía no tienes proveedores. Agrega uno y vincúlalo a esta línea.",
      openVendor: "Abrir proveedor",
    },
    shareText: (names: string, url: string, code: string) => `${names ? `${names} te invitan. ` : ""}Responde aquí: ${url} (código ${code})`,
  },
};

export type CoupleCopy = (typeof COPY)["en"];
